# Automatically generated by Pynguin.
import ansible.cli.inventory as module_0

def test_case_0():
    try:
        str_0 = ':D'
        inventory_c_l_i_0 = module_0.InventoryCLI(str_0)
        var_0 = inventory_c_l_i_0.run()
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = 222.093
        float_1 = 691.981
        inventory_c_l_i_0 = module_0.InventoryCLI(float_1)
        var_0 = inventory_c_l_i_0.dump(float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        float_0 = 60.0
        inventory_c_l_i_0 = module_0.InventoryCLI(float_0)
        var_0 = inventory_c_l_i_0.inventory_graph()
    except BaseException:
        pass

def test_case_3():
    try:
        bool_0 = True
        float_0 = 0.1
        str_0 = '!\x0c7Q+n'
        str_1 = 'xiZ]%/[}OC'
        dict_0 = {bool_0: bool_0, str_1: bool_0, bool_0: str_1, str_1: float_0}
        inventory_c_l_i_0 = module_0.InventoryCLI(dict_0)
        var_0 = inventory_c_l_i_0.json_inventory(str_0)
    except BaseException:
        pass

def test_case_4():
    try:
        bytes_0 = b'\x0c\xac\x99\xc47'
        str_0 = 'k'
        inventory_c_l_i_0 = module_0.InventoryCLI(str_0)
        var_0 = inventory_c_l_i_0.yaml_inventory(bytes_0)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = 'XGI\x0ba'
        inventory_c_l_i_0 = module_0.InventoryCLI(str_0)
        var_0 = inventory_c_l_i_0.toml_inventory(str_0)
    except BaseException:
        pass