# Automatically generated by Pynguin.
import ansible.plugins.action.pause as module_0

def test_case_0():
    try:
        bytes_0 = b'\xba\\\xf0\xf2'
        set_0 = {bytes_0, bytes_0, bytes_0, bytes_0}
        dict_0 = None
        var_0 = module_0.timeout_handler(set_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bool_0 = True
        var_0 = module_0.clear_line(bool_0)
    except BaseException:
        pass

def test_case_2():
    try:
        tuple_0 = ()
        list_0 = [tuple_0]
        ansible_timeout_exceeded_0 = module_0.AnsibleTimeoutExceeded()
        int_0 = -830
        bytes_0 = b'.\xea.\xc8\x8ad\x13t\xc1<M\xb9Z\xb0'
        float_0 = -1346.7
        action_module_0 = module_0.ActionModule(int_0, list_0, ansible_timeout_exceeded_0, tuple_0, bytes_0, float_0)
        var_0 = action_module_0.run()
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'invalid characters in salt'
        str_1 = 'xib\\:B'
        str_2 = 'EHn\r||u'
        dict_0 = {str_0: str_2, str_1: str_2}
        int_0 = -2877
        bool_0 = True
        float_0 = 1385.635269
        ansible_timeout_exceeded_0 = module_0.AnsibleTimeoutExceeded()
        dict_1 = {}
        bool_1 = False
        action_module_0 = module_0.ActionModule(ansible_timeout_exceeded_0, dict_1, int_0, bool_1, bool_1, int_0)
        int_1 = 60
        float_1 = -3498.440803
        action_module_1 = module_0.ActionModule(dict_0, float_0, action_module_0, int_1, float_1, int_0)
        var_0 = action_module_1.run(dict_0, bool_0)
    except BaseException:
        pass