# Automatically generated by Pynguin.
import string_utils.manipulation as module_0

def test_case_0():
    string_compressor_0 = module_0.__StringCompressor()

def test_case_1():
    int_0 = 3280
    str_0 = module_0.roman_encode(int_0)
    str_1 = module_0.slugify(str_0, str_0)
    str_2 = module_0.strip_margin(str_0)

def test_case_2():
    str_0 = 'c^xOJ;L)(I3`fe\\65i'
    str_1 = module_0.compress(str_0)

def test_case_3():
    str_0 = 'c^xOJ;L)(I3`fe\\65i'
    str_1 = module_0.prettify(str_0)

def test_case_4():
    str_0 = '8!@.X aQ8'
    str_1 = module_0.prettify(str_0)

def test_case_5():
    str_0 = 'Invalid card type "{}". Valid types are: {}'
    str_1 = module_0.prettify(str_0)
    str_2 = 'X;3='
    bool_0 = False
    str_3 = module_0.snake_case_to_camel(str_2, bool_0)

def test_case_6():
    str_0 = '\nMg+ZVB*[f\x0b'
    str_1 = module_0.prettify(str_0)

def test_case_7():
    str_0 = 'the_snake_is_green'
    str_1 = module_0.snake_case_to_camel(str_0)

def test_case_8():
    str_0 = 'X;3='
    bool_0 = True
    str_1 = module_0.snake_case_to_camel(str_0, bool_0)

def test_case_9():
    str_0 = 'the_snake_is_green'
    str_1 = module_0.shuffle(str_0)
    str_2 = module_0.prettify(str_0)
    str_3 = module_0.snake_case_to_camel(str_0)

def test_case_10():
    str_0 = 'r(O\\l\n'
    str_1 = module_0.strip_html(str_0)

def test_case_11():
    str_0 = 'SPACES_INSIDE'
    str_1 = module_0.slugify(str_0)

def test_case_12():
    str_0 = 'lTsGiDR'
    bool_0 = module_0.booleanize(str_0)

def test_case_13():
    str_0 = '8!@.X aQ8='
    str_1 = module_0.strip_margin(str_0)

def test_case_14():
    int_0 = 3357
    str_0 = 'a$2'
    str_1 = module_0.prettify(str_0)
    str_2 = module_0.compress(str_1)
    str_3 = module_0.roman_encode(int_0)
    string_formatter_0 = module_0.__StringFormatter(str_3)
    str_4 = "siT{uC5E2B,`g'Oj\rI"
    str_5 = module_0.strip_html(str_4)
    str_6 = 'R{,fBtf42\\GXv|G'
    int_1 = module_0.roman_decode(str_3)
    str_7 = module_0.shuffle(str_1)
    str_8 = module_0.snake_case_to_camel(str_6)
    bool_0 = False
    str_9 = module_0.snake_case_to_camel(str_7, bool_0)

def test_case_15():
    int_0 = 3269
    str_0 = module_0.roman_encode(int_0)
    str_1 = module_0.slugify(str_0, str_0)
    str_2 = module_0.strip_margin(str_0)

def test_case_16():
    str_0 = 'hello   world!  this is a test.  visit http://example.com or email me@example.com'
    str_1 = module_0.prettify(str_0)

def test_case_17():
    str_0 = 'ThisIsACamelStringTest'
    var_0 = module_0.camel_case_to_snake(str_0)

def test_case_18():
    str_0 = 'the_snake_is_green'
    bool_0 = None
    str_1 = module_0.snake_case_to_camel(str_0, bool_0)

def test_case_19():
    str_0 = '_heXsIake_is_green'
    str_1 = module_0.strip_margin(str_0)
    str_2 = module_0.prettify(str_0)
    bool_0 = True
    str_3 = module_0.snake_case_to_camel(str_2, bool_0)
    str_4 = "TnW4<uFaTD*?\r$_o'Nl}"
    str_5 = module_0.shuffle(str_4)