# Automatically generated by Pynguin.
import ansible.playbook.task_include as module_0

def test_case_0():
    task_include_0 = module_0.TaskInclude()

def test_case_1():
    task_include_0 = module_0.TaskInclude()
    var_0 = task_include_0.get_vars()

def test_case_2():
    task_include_0 = module_0.TaskInclude()
    var_0 = task_include_0.build_parent_block()

def test_case_3():
    task_include_0 = module_0.TaskInclude()
    str_0 = 'include'
    str_1 = {str_0: str_0}
    var_0 = task_include_0.load_data(str_1)
    var_1 = task_include_0.get_vars()

def test_case_4():
    task_include_0 = module_0.TaskInclude()
    str_0 = 'include'
    str_1 = {str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = task_include_0.load_data(str_1)
    var_1 = task_include_0.load_data(str_1)
    var_2 = task_include_0.check_options(var_1, str_0)