# Automatically generated by Pynguin.
import ansible.module_utils.common.text.converters as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = '=eN8%Swd$I'
    var_0 = module_0.container_to_bytes(str_0)

def test_case_2():
    dict_0 = {}
    var_0 = module_0.to_bytes(dict_0)

def test_case_3():
    list_0 = None
    bytes_0 = b'\xb9\x8f\xd3\x051\x0c'
    int_0 = 8
    tuple_0 = None
    bool_0 = False
    tuple_1 = (tuple_0, bool_0, bytes_0)
    var_0 = module_0.to_bytes(bytes_0, int_0, tuple_1)
    dict_0 = {list_0: list_0}
    var_1 = module_0.to_text(dict_0)

def test_case_4():
    str_0 = 'P$T'
    var_0 = module_0.to_text(str_0)

def test_case_5():
    dict_0 = {}
    var_0 = module_0.to_text(dict_0, dict_0)

def test_case_6():
    bytes_0 = b'\xa2\x9c'
    var_0 = module_0.to_text(bytes_0)

def test_case_7():
    str_0 = ".yU*y5<*g`fAJ'H^,"
    var_0 = module_0.jsonify(str_0)

def test_case_8():
    dict_0 = {}
    bool_0 = None
    var_0 = module_0.container_to_bytes(dict_0, bool_0)

def test_case_9():
    str_0 = '^;Dv'
    dict_0 = {str_0: str_0}
    var_0 = module_0.container_to_bytes(dict_0)

def test_case_10():
    str_0 = '+RnRi'
    var_0 = module_0.container_to_text(str_0)

def test_case_11():
    bytes_0 = b'\xde\x16\xf1\xc0'
    var_0 = module_0.jsonify(bytes_0)

def test_case_12():
    str_0 = 'vvuHdX9l.r'
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    var_0 = module_0.jsonify(dict_0)

def test_case_13():
    list_0 = []
    var_0 = module_0.jsonify(list_0)