# Automatically generated by Pynguin.
import mimesis.builtins.en as module_0

def test_case_0():
    try:
        str_0 = '\x0cU=sp8#s*'
        u_s_a_spec_provider_0 = module_0.USASpecProvider()
        str_1 = u_s_a_spec_provider_0.tracking_number(str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '/'
        u_s_a_spec_provider_0 = module_0.USASpecProvider()
        var_0 = u_s_a_spec_provider_0.personality(str_0)
        u_s_a_spec_provider_1 = module_0.USASpecProvider(str_0)
        u_s_a_spec_provider_2 = module_0.USASpecProvider()
        str_1 = u_s_a_spec_provider_2.ssn()
        str_2 = u_s_a_spec_provider_1.tracking_number(str_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '0bisVNyhk[2,'
        u_s_a_spec_provider_0 = module_0.USASpecProvider()
        var_0 = u_s_a_spec_provider_0.personality(str_0)
        u_s_a_spec_provider_1 = module_0.USASpecProvider()
        str_1 = u_s_a_spec_provider_1.ssn()
        str_2 = 'BT'
        u_s_a_spec_provider_2 = module_0.USASpecProvider()
        u_s_a_spec_provider_3 = module_0.USASpecProvider()
        str_3 = u_s_a_spec_provider_3.tracking_number()
        var_1 = u_s_a_spec_provider_3.personality(str_2)
        u_s_a_spec_provider_4 = module_0.USASpecProvider(str_2)
        str_4 = u_s_a_spec_provider_4.tracking_number()
        u_s_a_spec_provider_5 = module_0.USASpecProvider()
        str_5 = u_s_a_spec_provider_5.ssn()
        str_6 = u_s_a_spec_provider_4.ssn()
        str_7 = u_s_a_spec_provider_5.ssn()
        str_8 = u_s_a_spec_provider_5.ssn()
        var_2 = u_s_a_spec_provider_0.personality()
        str_9 = u_s_a_spec_provider_0.ssn()
        str_10 = u_s_a_spec_provider_5.tracking_number()
        str_11 = 'A(,:_0$/\tmf%rqU{|>'
        var_3 = u_s_a_spec_provider_5.personality(str_11)
        u_s_a_spec_provider_6 = module_0.USASpecProvider()
        str_12 = u_s_a_spec_provider_5.tracking_number()
        u_s_a_spec_provider_7 = module_0.USASpecProvider(str_7)
        var_4 = u_s_a_spec_provider_6.personality()
        var_5 = u_s_a_spec_provider_0.personality()
        u_s_a_spec_provider_8 = module_0.USASpecProvider(str_2)
        str_13 = u_s_a_spec_provider_4.ssn()
        u_s_a_spec_provider_9 = module_0.USASpecProvider(str_3)
        str_14 = u_s_a_spec_provider_9.tracking_number()
        str_15 = 'll[u#'
        str_16 = u_s_a_spec_provider_0.tracking_number(str_15)
    except BaseException:
        pass

def test_case_3():
    try:
        u_s_a_spec_provider_0 = module_0.USASpecProvider()
        str_0 = '<.?+'
        str_1 = u_s_a_spec_provider_0.ssn()
        str_2 = u_s_a_spec_provider_0.tracking_number()
        str_3 = u_s_a_spec_provider_0.tracking_number()
        str_4 = u_s_a_spec_provider_0.ssn()
        u_s_a_spec_provider_1 = module_0.USASpecProvider()
        str_5 = 'rheti'
        var_0 = u_s_a_spec_provider_0.personality(str_5)
        str_6 = 'ascension'
        var_1 = u_s_a_spec_provider_1.personality(str_6)
        str_7 = u_s_a_spec_provider_0.tracking_number()
        str_8 = u_s_a_spec_provider_0.ssn()
        str_9 = u_s_a_spec_provider_1.ssn()
        var_2 = u_s_a_spec_provider_0.personality(str_7)
        str_10 = u_s_a_spec_provider_0.ssn()
        u_s_a_spec_provider_2 = module_0.USASpecProvider(str_4)
        var_3 = u_s_a_spec_provider_2.personality()
        var_4 = u_s_a_spec_provider_1.personality(str_8)
        u_s_a_spec_provider_3 = module_0.USASpecProvider()
        str_11 = u_s_a_spec_provider_0.ssn()
        u_s_a_spec_provider_4 = module_0.USASpecProvider()
        str_12 = u_s_a_spec_provider_4.ssn()
        u_s_a_spec_provider_5 = module_0.USASpecProvider()
        u_s_a_spec_provider_6 = module_0.USASpecProvider()
        str_13 = u_s_a_spec_provider_6.tracking_number()
        u_s_a_spec_provider_7 = module_0.USASpecProvider(str_3)
        var_5 = u_s_a_spec_provider_7.personality()
        u_s_a_spec_provider_8 = module_0.USASpecProvider(str_0)
        str_14 = '_8On9FE+U2] ^B/'
        str_15 = u_s_a_spec_provider_5.tracking_number(str_14)
    except BaseException:
        pass