# Automatically generated by Pynguin.
import ansible.plugins.inventory.constructed as module_0

def test_case_0():
    try:
        float_0 = 699.355986
        int_0 = -1334
        str_0 = '|LTZb'
        inventory_module_0 = module_0.InventoryModule()
        var_0 = inventory_module_0.get_all_host_vars(float_0, int_0, str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        inventory_module_0 = module_0.InventoryModule()
        int_0 = None
        str_0 = 'marker'
        str_1 = '{'
        var_0 = inventory_module_0.host_vars(int_0, str_0, str_1)
    except BaseException:
        pass

def test_case_2():
    try:
        inventory_module_0 = module_0.InventoryModule()
        bool_0 = True
        list_0 = []
        inventory_module_1 = module_0.InventoryModule()
        var_0 = inventory_module_1.parse(inventory_module_0, bool_0, bool_0, list_0)
    except BaseException:
        pass

def test_case_3():
    try:
        float_0 = None
        str_0 = 'Sending become_password in response to prompt'
        list_0 = [float_0, str_0, float_0, float_0]
        inventory_module_0 = None
        str_1 = 'H\\j:2%<JuN=hMa 6:c;'
        float_1 = -3728.3596
        tuple_0 = (str_0, list_0, list_0, float_1)
        tuple_1 = (str_1, tuple_0)
        bool_0 = False
        tuple_2 = (list_0, inventory_module_0, tuple_1, bool_0)
        inventory_module_1 = module_0.InventoryModule()
        var_0 = inventory_module_1.parse(tuple_2, bool_0, tuple_0)
    except BaseException:
        pass