# Automatically generated by Pynguin.
import httpie.utils as module_0

def test_case_0():
    explicit_null_auth_0 = module_0.ExplicitNullAuth()

def test_case_1():
    str_0 = '_xample.txt'
    var_0 = module_0.get_content_type(str_0)
    dict_0 = {str_0: str_0, str_0: str_0}
    str_1 = module_0.repr_dict(dict_0)

def test_case_2():
    float_0 = 0.1
    var_0 = module_0.humanize_bytes(float_0)

def test_case_3():
    str_0 = '#=\\jM\\'
    var_0 = module_0.get_content_type(str_0)
    bool_0 = True
    explicit_null_auth_0 = module_0.ExplicitNullAuth()
    var_1 = explicit_null_auth_0.__call__(bool_0)

def test_case_4():
    str_0 = 'example.txt'
    var_0 = module_0.get_content_type(str_0)

def test_case_5():
    list_0 = []
    list_1 = module_0.get_expired_cookies(list_0)

def test_case_6():
    str_0 = 'g;Q*!czWNR\x0c*D8,U`'
    tuple_0 = (str_0, str_0)
    list_0 = [tuple_0]
    list_1 = module_0.get_expired_cookies(list_0)

def test_case_7():
    str_0 = 'by\\*,XTP2 \\f(xoBRhQ'
    var_0 = module_0.get_content_type(str_0)

def test_case_8():
    str_0 = 'Pexample.txt'
    var_0 = module_0.get_content_type(str_0)
    float_0 = -260.7060259746091
    list_0 = []
    list_1 = module_0.get_expired_cookies(list_0, float_0)

def test_case_9():
    float_0 = -3196.8631186480943
    int_0 = 12
    var_0 = module_0.humanize_bytes(int_0)
    str_0 = 'tt4Cyk'
    tuple_0 = (str_0, str_0)
    list_0 = [tuple_0, tuple_0]
    list_1 = module_0.get_expired_cookies(list_0, float_0)

def test_case_10():
    float_0 = -3196.8631186480943
    int_0 = 1
    var_0 = module_0.humanize_bytes(int_0)
    str_0 = 'tt4Cyk'
    tuple_0 = (str_0, str_0)
    list_0 = [tuple_0, tuple_0]
    list_1 = module_0.get_expired_cookies(list_0, float_0)

def test_case_11():
    str_0 = 'Set-Cookie'
    tuple_0 = (str_0, str_0)
    list_0 = [tuple_0, tuple_0, tuple_0, tuple_0]
    list_1 = module_0.get_expired_cookies(list_0)

def test_case_12():
    str_0 = 'Set-Cookie'
    str_1 = 'sessionid=abc1[3; Max-Age=3600; Peth=/'
    tuple_0 = (str_0, str_1)
    list_0 = [tuple_0]
    list_1 = module_0.get_expired_cookies(list_0)

def test_case_13():
    str_0 = 'Set-Cookie'
    str_1 = 'userid=xy:789; Expires=Wed, 0t Jun22021 10:18:14 GMT; Path=/'
    tuple_0 = (str_0, str_1)
    list_0 = [tuple_0]
    list_1 = module_0.get_expired_cookies(list_0)

def test_case_14():
    str_0 = 'Set-Cookie'
    str_1 = 'sessionid=abc123; Max-Age=3600h Path=/'
    tuple_0 = (str_0, str_1)
    list_0 = [tuple_0]
    list_1 = module_0.get_expired_cookies(list_0)
    str_2 = 'yf=o]pgH<'
    list_2 = module_0.get_expired_cookies(list_0, str_2)