# Automatically generated by Pynguin.
import ansible.utils.unsafe_proxy as module_0

def test_case_0():
    ansible_unsafe_text_0 = module_0.AnsibleUnsafeText()

def test_case_1():
    ansible_unsafe_text_0 = module_0.AnsibleUnsafeText()
    var_0 = ansible_unsafe_text_0.encode()
    var_1 = ansible_unsafe_text_0.encode()
    int_0 = 117
    var_2 = module_0.wrap_var(int_0)

def test_case_2():
    str_0 = '+"t2p.}Xb\x0b]'
    var_0 = module_0.wrap_var(str_0)

def test_case_3():
    int_0 = 132
    var_0 = module_0.wrap_var(int_0)

def test_case_4():
    bytes_0 = b'\xc4\xc4\x81\xa9\x9c\xbc\xc7\xeb\xe0roh\xb1M\x8f\x15\xeav\xc7\x86'
    var_0 = module_0.wrap_var(bytes_0)

def test_case_5():
    ansible_unsafe_text_0 = module_0.AnsibleUnsafeText()
    var_0 = ansible_unsafe_text_0.encode()
    float_0 = -1507.0
    list_0 = [float_0, float_0]
    var_1 = ansible_unsafe_text_0.encode()
    int_0 = 117
    var_2 = module_0.wrap_var(int_0)
    unsafe_proxy_0 = module_0.UnsafeProxy(*list_0)