# Automatically generated by Pynguin.
import ansible.inventory.group as module_0

def test_case_0():
    group_0 = module_0.Group()

def test_case_1():
    str_0 = '9e3t_grRup'
    group_0 = module_0.Group(str_0)

def test_case_2():
    group_0 = module_0.Group()
    var_0 = group_0.__str__()

def test_case_3():
    str_0 = 'P+WZ@~_J^<w%'
    dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
    tuple_0 = ()
    group_0 = module_0.Group(tuple_0)
    var_0 = group_0.deserialize(dict_0)

def test_case_4():
    group_0 = module_0.Group()
    var_0 = group_0.get_hosts()

def test_case_5():
    group_0 = module_0.Group()
    group_1 = module_0.Group()
    var_0 = group_1.add_child_group(group_0)

def test_case_6():
    group_0 = module_0.Group()
    var_0 = group_0.remove_host(group_0)

def test_case_7():
    group_0 = module_0.Group()
    group_1 = module_0.Group()
    var_0 = group_1.set_variable(group_0, group_0)

def test_case_8():
    group_0 = module_0.Group()
    group_1 = module_0.Group()
    var_0 = group_1.add_child_group(group_0)
    var_1 = group_1.get_vars()

def test_case_9():
    str_0 = 'BU7C<`'
    group_0 = module_0.Group()
    var_0 = group_0.get_hosts()
    group_1 = module_0.Group()
    var_1 = group_0.add_child_group(group_1)
    list_0 = [var_1]
    var_2 = group_1.get_descendants()
    var_3 = module_0.to_safe_group_name(str_0, str_0, list_0)
    var_4 = group_1.remove_host(group_1)
    var_5 = group_1.get_ancestors()
    group_2 = module_0.Group()
    var_6 = group_1.__getstate__()
    var_7 = group_1.serialize()
    group_3 = module_0.Group()

def test_case_10():
    group_0 = module_0.Group()
    group_1 = module_0.Group()
    var_0 = group_0.add_child_group(group_1)
    var_1 = group_0.get_hosts()

def test_case_11():
    str_0 = 'tt_voup'
    group_0 = module_0.Group(str_0)

def test_case_12():
    group_0 = module_0.Group()
    group_1 = module_0.Group()
    group_2 = module_0.Group()
    var_0 = group_1.add_child_group(group_2)
    var_1 = group_1.get_name()
    var_2 = group_2.remove_host(group_2)
    var_3 = group_0.add_child_group(group_1)
    var_4 = group_2.get_ancestors()