# Automatically generated by Pynguin.
import ansible.module_utils.common.json as module_0

def test_case_0():
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder()

def test_case_1():
    complex_0 = None
    list_0 = [complex_0, complex_0, complex_0]
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder(list_0)
    var_0 = ansible_j_s_o_n_encoder_0.iterencode(complex_0)

def test_case_2():
    complex_0 = None
    list_0 = [complex_0, complex_0, complex_0]
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder(list_0)
    var_0 = ansible_j_s_o_n_encoder_0.iterencode(list_0)

def test_case_3():
    bool_0 = None
    dict_0 = {bool_0: bool_0}
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder()
    var_0 = ansible_j_s_o_n_encoder_0.default(dict_0)

def test_case_4():
    str_0 = ';G:m'
    str_1 = None
    str_2 = 'ynMB&cw Yo)]C:}%n'
    dict_0 = {str_1: str_0, str_2: str_2}
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder()
    var_0 = ansible_j_s_o_n_encoder_0.default(dict_0)
    list_0 = [str_1]
    var_1 = ansible_j_s_o_n_encoder_0.iterencode(list_0)

def test_case_5():
    dict_0 = {}
    float_0 = 2954.519
    ansible_j_s_o_n_encoder_0 = module_0.AnsibleJSONEncoder(float_0)
    var_0 = ansible_j_s_o_n_encoder_0.iterencode(dict_0)