# Automatically generated by Pynguin.
import ansible.cli.inventory as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = '3lw_+Ehg_CNM5'
    inventory_c_l_i_0 = module_0.InventoryCLI(str_0)

def test_case_2():
    str_0 = '_v\r|}0)B=4`Q@A'
    inventory_c_l_i_0 = module_0.InventoryCLI(str_0)
    var_0 = inventory_c_l_i_0.init_parser()