# Automatically generated by Pynguin.
import pypara.monetary as module_0
import pypara.currencies as module_1
import decimal as module_2
import datetime as module_3

def test_case_0():
    pass

def test_case_1():
    int_0 = -544
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.round(int_0)
    var_0 = money_0.__round__()
    str_0 = '7G\x0b\tY.!M$K n'
    str_1 = ':6'
    int_1 = 30
    currency_type_0 = module_1.CurrencyType.METAL
    decimal_0 = None
    currency_0 = module_1.Currency(str_0, str_1, int_1, currency_type_0, decimal_0, int_1)
    incompatible_currency_error_0 = module_0.IncompatibleCurrencyError(currency_0, currency_0, str_0)

def test_case_2():
    list_0 = []
    str_0 = "oe'T8\rC*Y%`]\x0clTVlz;"
    str_1 = 'l9^\rU)lTXC8i$,w5<p'
    int_0 = -1281
    currency_type_0 = module_1.CurrencyType.ALTERNATIVE
    decimal_0 = module_2.Decimal()
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.with_ccy(currency_0)
    money_1 = money_0.__abs__()
    money_2 = money_1.divide(list_0)

def test_case_3():
    int_0 = 1167
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.round(int_0)
    var_0 = price_0.__round__()
    var_1 = None
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.divide(var_1)
    money_1 = money_0.__mul__(var_1)
    money_2 = money_0.__sub__(money_0)
    money_3 = money_2.round()

def test_case_4():
    str_0 = None
    str_1 = 'zm4:PZZI)Mmm^5.>b\t6'
    int_0 = -446
    currency_type_0 = module_1.CurrencyType.ALTERNATIVE
    list_0 = []
    decimal_0 = module_2.Decimal(*list_0)
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    list_1 = []
    none_money_0 = module_0.NoneMoney(*list_1)
    money_0 = none_money_0.with_ccy(currency_0)

def test_case_5():
    int_0 = 1525
    str_0 = '\'G@\'H\x0cKy>Z"C_S+9+fN'
    str_1 = 'H5l8z-l=k\x0bX'
    dict_0 = {}
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.scalar_subtract(dict_0)
    int_1 = 0
    currency_type_0 = module_1.CurrencyType.METAL
    decimal_0 = module_2.Decimal()
    int_2 = -806
    currency_0 = module_1.Currency(str_0, str_1, int_1, currency_type_0, decimal_0, int_2)
    bytes_0 = b'nK\r\xe1s\xef\x9d<2\xd4\xca~\x0e\x89\xc0'
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.floor_divide(bytes_0)
    money_1 = money_0.with_ccy(currency_0)
    money_2 = money_1.round(int_0)

def test_case_6():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.positive()
    decimal_0 = module_2.Decimal()
    price_1 = none_price_0.with_qty(decimal_0)
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    dict_0 = {}
    price_2 = none_price_0.subtract(price_1)
    none_money_0 = module_0.NoneMoney(**dict_0)
    money_0 = some_money_0.abs()
    bool_0 = money_0.lte(money_0)
    money_1 = money_0.__sub__(money_0)
    bool_1 = money_1.__lt__(money_0)

def test_case_7():
    str_0 = '\'G@\'H\x0cKy>Z"C_S+9+fN'
    str_1 = 'H5l8z-l=k\x0bX'
    none_price_0 = module_0.NonePrice()
    int_0 = 0
    currency_type_0 = module_1.CurrencyType.METAL
    decimal_0 = module_2.Decimal()
    int_1 = -806
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_1)
    none_money_0 = module_0.NoneMoney()
    none_price_1 = module_0.NonePrice()
    bool_0 = none_price_1.is_equal(none_price_0)
    price_0 = none_price_0.negative()

def test_case_8():
    none_money_0 = module_0.NoneMoney()
    var_0 = None
    money_0 = none_money_0.scalar_subtract(var_0)

def test_case_9():
    list_0 = []
    str_0 = "oe'T8\rC*Y%`]\x0clTVlz;"
    str_1 = 'l9^\rU)lTXC8i$,w5<p'
    int_0 = -1281
    currency_type_0 = module_1.CurrencyType.ALTERNATIVE
    decimal_0 = module_2.Decimal()
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.with_ccy(currency_0)
    money_1 = money_0.__abs__()
    bool_0 = none_money_0.gte(money_1)
    money_2 = money_1.divide(list_0)

def test_case_10():
    list_0 = []
    none_money_0 = module_0.NoneMoney(*list_0)
    currency_type_0 = module_1.CurrencyType.METAL
    decimal_0 = None
    int_0 = 0
    str_0 = '90 AXz}'
    str_1 = 'Account name, code and parent do not match existing chart of accounts member.'
    int_1 = 4
    currency_0 = module_1.Currency(str_0, str_1, int_1, currency_type_0, decimal_0, int_0)
    money_0 = none_money_0.with_ccy(currency_0)
    money_1 = none_money_0.with_qty(decimal_0)
    var_0 = None
    money_2 = money_1.__mul__(var_0)
    money_3 = money_0.__abs__()
    incompatible_currency_error_0 = module_0.IncompatibleCurrencyError(currency_0, currency_0)

def test_case_11():
    bytes_0 = b'\xd8\x9b'
    none_price_0 = module_0.NonePrice()
    str_0 = 'P`V(mH<[5o8['
    str_1 = '#P}/'
    int_0 = 3606
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    price_0 = none_price_0.with_ccy(currency_0)
    price_1 = none_price_0.positive()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    bool_0 = some_money_0.is_equal(bytes_0)
    dict_0 = {}
    none_money_0 = module_0.NoneMoney(**dict_0)
    money_0 = some_money_0.abs()
    money_1 = money_0.__add__(money_0)
    bool_1 = money_0.lte(money_1)
    money_2 = money_0.positive()
    var_0 = price_0.__round__()

def test_case_12():
    int_0 = 1525
    str_0 = '\'G@\'H\x0cKy>Z"C_S+9+fN'
    str_1 = 'H5l8z-l=k\x0bX'
    none_price_0 = module_0.NonePrice()
    int_1 = 0
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    int_2 = -806
    currency_0 = module_1.Currency(str_0, str_1, int_1, currency_type_0, decimal_0, int_2)
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.negative()
    money_1 = money_0.__sub__(money_0)
    money_2 = money_1.round(int_0)
    price_0 = none_price_0.abs()

def test_case_13():
    str_0 = '\'G@\'H\x0cKy>Z"C_S+9+fN'
    str_1 = 'H5l8z-l=k\x0bX'
    none_price_0 = module_0.NonePrice()
    int_0 = 0
    currency_type_0 = module_1.CurrencyType.METAL
    decimal_0 = module_2.Decimal()
    str_2 = '0vTuc;|5bXZ]#f'
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.multiply(str_2)
    none_money_1 = module_0.NoneMoney()
    money_1 = none_money_1.with_qty(decimal_0)
    bool_0 = money_1.__gt__(money_0)
    int_1 = -806
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_1)
    none_money_2 = module_0.NoneMoney()
    money_2 = none_money_2.negative()
    var_0 = None
    money_3 = money_2.__mul__(var_0)
    money_4 = money_2.__sub__(money_3)
    money_5 = money_2.round()

def test_case_14():
    int_0 = 1167
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.round(int_0)
    var_0 = price_0.__round__()

def test_case_15():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.abs()
    decimal_0 = module_2.Decimal()
    price_1 = none_price_0.with_qty(decimal_0)
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    dict_0 = {}
    none_money_0 = module_0.NoneMoney(**dict_0)
    var_0 = None
    price_2 = price_1.scalar_add(var_0)
    some_price_0 = module_0.SomePrice(*list_0, **dict_0)
    price_3 = some_price_0.subtract(price_2)
    bool_0 = price_3.gte(price_3)
    price_4 = some_price_0.add(price_3)

def test_case_16():
    bytes_0 = b'\xd8\x9b'
    none_price_0 = module_0.NonePrice()
    int_0 = 3606
    price_0 = none_price_0.positive()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    bool_0 = some_money_0.is_equal(bytes_0)
    dict_0 = {}
    none_money_0 = module_0.NoneMoney(**dict_0)
    money_0 = some_money_0.abs()
    money_1 = money_0.__add__(money_0)
    bool_1 = money_0.lte(money_0)
    money_2 = money_0.positive()
    price_1 = module_0.Price()
    var_0 = price_0.__round__(int_0)

def test_case_17():
    int_0 = 1167
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.round(int_0)
    var_0 = price_0.__round__()
    bool_0 = none_price_0.as_boolean()
    none_money_0 = module_0.NoneMoney()

def test_case_18():
    bytes_0 = b'\xd8\x9b'
    none_price_0 = module_0.NonePrice()
    str_0 = 'P`V(mH<[5o8['
    str_1 = '#P}/'
    int_0 = 3606
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    bool_0 = some_money_0.is_equal(bytes_0)
    dict_0 = {}
    none_money_0 = module_0.NoneMoney(**dict_0)
    money_0 = some_money_0.abs()
    bool_1 = money_0.__gt__(money_0)
    str_2 = 'Kuwaiti Dinar'
    some_price_0 = module_0.SomePrice(*list_0)
    price_0 = none_price_0.negative()
    price_1 = some_price_0.subtract(price_0)
    currency_type_1 = module_1.CurrencyType.METAL
    int_1 = 31
    int_2 = 360
    currency_1 = module_1.Currency(str_2, str_2, int_1, currency_type_1, decimal_0, int_2)
    price_2 = some_price_0.with_ccy(currency_1)
    price_3 = price_1.positive()
    price_4 = price_0.convert(currency_1)

def test_case_19():
    none_price_0 = module_0.NonePrice()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    some_price_0 = module_0.SomePrice(*list_0)
    money_0 = some_money_0.abs()
    bool_0 = money_0.__gt__(money_0)

def test_case_20():
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_price_0 = module_0.SomePrice(*list_0)
    price_0 = some_price_0.abs()
    price_1 = some_price_0.subtract(price_0)
    date_0 = None
    price_2 = some_price_0.add(price_0)
    price_3 = price_1.with_dov(date_0)
    bool_0 = price_2.__le__(price_3)

def test_case_21():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.abs()
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    bool_0 = none_price_0.lte(price_0)
    some_price_0 = module_0.SomePrice(*list_0)
    bool_1 = some_price_0.gt(price_0)
    price_1 = price_0.with_qty(decimal_0)
    price_2 = price_0.__pos__()
    bool_2 = none_price_0.gte(price_0)
    bool_3 = price_0.gte(price_2)
    price_3 = some_price_0.subtract(price_0)
    price_4 = some_price_0.subtract(price_3)
    price_5 = price_4.__abs__()
    bool_4 = price_5.__lt__(price_5)

def test_case_22():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.negative()
    decimal_0 = module_2.Decimal()
    price_1 = none_price_0.with_qty(decimal_0)
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    dict_0 = {}
    price_2 = none_price_0.subtract(price_1)
    none_money_0 = module_0.NoneMoney(**dict_0)
    price_3 = module_0.Price()
    some_price_0 = module_0.SomePrice(*list_0, **dict_0)
    price_4 = some_price_0.subtract(price_0)
    price_5 = some_price_0.add(price_2)

def test_case_23():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.negative()
    str_0 = 'P`V(mH<[5o8['
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    price_1 = none_price_0.with_qty(decimal_0)
    float_0 = -1884.952
    list_0 = [str_0, currency_type_0, price_1, str_0, price_1]
    price_2 = price_1.scalar_add(list_0)
    list_1 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_1)
    dict_0 = {}
    var_0 = None
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.floor_divide(var_0)
    bool_0 = some_money_0.gt(money_0)
    price_3 = none_price_0.subtract(price_1)
    none_money_1 = module_0.NoneMoney(**dict_0)
    money_1 = some_money_0.abs()
    bool_1 = money_1.__gt__(money_1)
    money_2 = money_1.__add__(money_1)
    money_3 = some_money_0.abs()
    bool_2 = money_1.lte(money_3)
    money_4 = money_1.__sub__(money_3)
    bool_3 = money_2.__lt__(money_3)
    price_4 = module_0.Price()
    money_5 = money_2.negative()
    some_price_0 = module_0.SomePrice(*list_1, **dict_0)
    price_5 = some_price_0.subtract(price_2)
    price_6 = some_price_0.add(price_2)

def test_case_24():
    none_price_0 = module_0.NonePrice()
    str_0 = 'i:Gh>\tzI8D*<'
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_price_0 = module_0.SomePrice(*list_0)
    price_0 = some_price_0.abs()
    currency_type_0 = module_1.CurrencyType.METAL
    bool_0 = price_0.gte(price_0)
    price_1 = some_price_0.subtract(price_0)
    price_2 = price_1.negative()
    bool_1 = price_2.__lt__(price_0)
    str_1 = 'CBu)h2]M*'
    int_0 = 29
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    date_0 = None
    price_3 = some_price_0.add(price_1)
    bool_2 = price_1.__gt__(price_1)
    price_4 = price_1.with_dov(date_0)

def test_case_25():
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    money_0 = some_money_0.abs()
    bool_0 = money_0.__gt__(money_0)
    money_1 = money_0.__add__(money_0)
    money_2 = some_money_0.abs()
    bool_1 = money_0.lte(money_2)
    money_3 = money_0.__sub__(money_2)
    bool_2 = money_1.__lt__(money_2)
    str_0 = 'Kuwaiti Dinar'
    int_0 = None
    currency_type_0 = module_1.CurrencyType.CRYPTO
    float_1 = money_0.as_float()
    str_1 = None
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    float_2 = money_0.__float__()
    money_4 = some_money_0.with_ccy(currency_0)
    bool_3 = some_money_0.gte(money_2)

def test_case_26():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.negative()
    str_0 = 'P`V(mH<[5o8['
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [str_0, currency_type_0, price_0, str_0, price_0]
    price_1 = price_0.scalar_add(list_0)
    list_1 = [float_0, float_0, float_0]
    dict_0 = {}
    price_2 = none_price_0.subtract(price_0)
    none_money_0 = module_0.NoneMoney(**dict_0)
    price_3 = module_0.Price()
    str_1 = 'Kuwaiti Dinar'
    int_0 = None
    currency_type_1 = module_1.CurrencyType.CRYPTO
    some_price_0 = module_0.SomePrice(*list_1, **dict_0)
    price_4 = some_price_0.subtract(price_1)
    bool_0 = price_4.gte(price_1)
    str_2 = None
    bool_1 = some_price_0.as_boolean()
    currency_0 = module_1.Currency(str_1, str_2, int_0, currency_type_1, decimal_0, int_0)
    price_5 = some_price_0.add(price_2)

def test_case_27():
    bytes_0 = b'\xd8\x9b'
    none_price_0 = module_0.NonePrice()
    str_0 = "Zf|'`9\n<f\x0b"
    int_0 = 3606
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    currency_0 = module_1.Currency(str_0, str_0, int_0, currency_type_0, decimal_0, int_0)
    price_0 = none_price_0.with_qty(decimal_0)
    price_1 = price_0.add(price_0)
    price_2 = none_price_0.positive()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_0)
    money_0 = some_money_0.negative()
    bool_0 = money_0.is_equal(price_1)
    bool_1 = some_money_0.is_equal(bytes_0)
    str_1 = 'KR)e_Z'
    money_1 = money_0.negative()
    some_price_0 = module_0.SomePrice(*list_0)
    price_3 = some_price_0.subtract(price_1)
    bool_2 = price_0.gte(price_1)
    str_2 = ".vgU~:'s.d#"
    price_4 = price_0.with_ccy(currency_0)
    currency_1 = module_1.Currency(str_1, str_2, int_0, currency_type_0, decimal_0, int_0)
    price_5 = some_price_0.add(price_3)
    bool_3 = price_3.__le__(price_3)
    str_3 = '\te8#\x0cVf!;^)'
    money_2 = money_0.__floordiv__(str_3)
    bool_4 = some_money_0.gte(money_2)

def test_case_28():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.positive()
    str_0 = 'P`V(mH<[5o8['
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    price_1 = none_price_0.with_qty(decimal_0)
    float_0 = -1884.952
    list_0 = [str_0, currency_type_0, price_1, str_0, price_1]
    price_2 = price_1.scalar_add(list_0)
    list_1 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_1)
    dict_0 = {}
    price_3 = none_price_0.subtract(price_1)
    none_money_0 = module_0.NoneMoney(**dict_0)
    money_0 = some_money_0.abs()
    bool_0 = money_0.__gt__(money_0)
    money_1 = money_0.__add__(money_0)
    money_2 = money_1.abs()
    money_3 = money_0.__sub__(money_2)
    bool_1 = money_1.__lt__(money_2)
    price_4 = module_0.Price()
    bool_2 = none_money_0.lt(money_0)
    float_1 = money_0.as_float()
    some_price_0 = module_0.SomePrice(*list_1, **dict_0)
    price_5 = some_price_0.subtract(price_2)
    bool_3 = price_5.gte(price_2)
    price_6 = price_0.__add__(price_3)
    price_7 = some_price_0.add(price_3)
    str_1 = 'FvwtRf'
    money_4 = some_money_0.divide(str_1)

def test_case_29():
    none_price_0 = module_0.NonePrice()
    price_0 = none_price_0.abs()
    str_0 = 'i:Gh>\tzI8D*<'
    currency_type_0 = module_1.CurrencyType.MONEY
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [str_0, currency_type_0, price_0, str_0, price_0]
    list_1 = [float_0, float_0, float_0]
    some_money_0 = module_0.SomeMoney(*list_1)
    dict_0 = {}
    none_money_0 = module_0.NoneMoney(**dict_0)
    some_price_0 = module_0.SomePrice(*list_1)
    bool_0 = some_price_0.gt(price_0)
    money_0 = some_money_0.abs()
    bool_1 = money_0.__gt__(money_0)
    money_1 = money_0.__add__(money_0)
    bool_2 = some_price_0.is_equal(bool_1)
    money_2 = money_0.__sub__(money_1)
    bool_3 = money_1.__lt__(money_0)
    float_1 = money_2.as_float()
    some_price_1 = module_0.SomePrice(*list_1)
    price_1 = some_price_0.subtract(price_0)
    bool_4 = price_0.gte(price_0)
    price_2 = some_price_0.subtract(price_1)
    price_3 = price_1.__abs__()
    bool_5 = price_2.__lt__(price_1)
    bool_6 = price_3.__lt__(price_1)
    money_3 = none_price_0.times(list_0)
    price_4 = module_0.Price()
    price_5 = none_price_0.abs()
    str_1 = 'EXPENSES'
    price_6 = some_price_0.divide(str_1)

def test_case_30():
    str_0 = 'i:Gh>\tzI8D*<'
    decimal_0 = module_2.Decimal()
    float_0 = -1884.952
    list_0 = [float_0, float_0, float_0]
    some_price_0 = module_0.SomePrice(*list_0)
    price_0 = some_price_0.abs()
    currency_type_0 = module_1.CurrencyType.METAL
    price_1 = some_price_0.subtract(price_0)
    price_2 = some_price_0.subtract(price_1)
    price_3 = price_0.__abs__()
    bool_0 = price_1.__lt__(price_0)
    str_1 = 'CBu)h2]M*'
    int_0 = 29
    currency_0 = module_1.Currency(str_0, str_1, int_0, currency_type_0, decimal_0, int_0)
    date_0 = None
    price_4 = some_price_0.add(price_2)
    bool_1 = price_1.__gt__(price_2)
    price_5 = price_2.with_dov(date_0)
    bool_2 = price_5.__le__(price_4)

def test_case_31():
    bool_0 = True
    list_0 = [bool_0, bool_0, bool_0]
    date_0 = module_3.date(*list_0)
    none_money_0 = module_0.NoneMoney()
    money_0 = none_money_0.with_dov(date_0)