# Automatically generated by Pynguin.
import ansible.module_utils.common.arg_spec as module_0

def test_case_0():
    bytes_0 = b'\x91\xf5\xdf\x1a\xf9'
    list_0 = [bytes_0, bytes_0, bytes_0]
    dict_0 = {}
    bool_0 = False
    argument_spec_validator_0 = module_0.ArgumentSpecValidator(dict_0, bool_0)
    var_0 = argument_spec_validator_0.validate(dict_0, *list_0)

def test_case_1():
    bytes_0 = b'6\xdd@\xacA\x8a\x9dK\xbeb\xae'
    list_0 = [bytes_0, bytes_0, bytes_0]
    dict_0 = {}
    float_0 = 100.0
    validation_result_0 = module_0.ValidationResult(float_0)
    argument_spec_validator_0 = module_0.ArgumentSpecValidator(dict_0, dict_0, list_0, validation_result_0)
    str_0 = ''
    dict_1 = {str_0: bytes_0, str_0: dict_0, str_0: validation_result_0}
    var_0 = argument_spec_validator_0.validate(dict_1, *list_0)

def test_case_2():
    bytes_0 = b'6\xdd@\xacA\x8a\x9dK\xbeb\xaeN'
    list_0 = [bytes_0, bytes_0, bytes_0]
    dict_0 = {}
    str_0 = '3;Hl;`<A'
    dict_1 = {str_0: list_0, str_0: str_0, str_0: dict_0}
    argument_spec_validator_0 = module_0.ArgumentSpecValidator(dict_1)