# Automatically generated by Pynguin.
import httpie.plugins.manager as module_0

def test_case_0():
    try:
        type_0 = None
        plugin_manager_0 = module_0.PluginManager()
        var_0 = plugin_manager_0.unregister(type_0)
    except BaseException:
        pass

def test_case_1():
    try:
        plugin_manager_0 = module_0.PluginManager()
        list_0 = plugin_manager_0.get_formatters()
        list_1 = plugin_manager_0.get_formatters()
        var_0 = plugin_manager_0.load_installed_plugins()
        str_0 = '|~|st \rjGRM/4WRj7Vu'
        type_0 = plugin_manager_0.get_auth_plugin(str_0)
    except BaseException:
        pass

def test_case_2():
    try:
        plugin_manager_0 = module_0.PluginManager()
        var_0 = plugin_manager_0.filter()
        bytes_0 = None
        list_0 = [bytes_0]
        var_1 = plugin_manager_0.register(*list_0)
        list_1 = plugin_manager_0.get_converters()
    except BaseException:
        pass