# Automatically generated by Pynguin.
import ansible.parsing.utils.jsonify as module_0

def test_case_0():
    try:
        bytes_0 = b'\x027V\x15#'
        var_0 = module_0.jsonify(bytes_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bytes_0 = b'|\x1cD_\xec\x8c\xb0G\xfa\x12#\x13'
        var_0 = module_0.jsonify(bytes_0, bytes_0)
    except BaseException:
        pass