# Automatically generated by Pynguin.
import pytutils.urls as module_0

def test_case_0():
    try:
        str_0 = 'R;Qadqb&Z6hQ'
        list_0 = [str_0]
        var_0 = module_0.update_query_params(str_0, list_0)
    except BaseException:
        pass