# Automatically generated by Pynguin.
import ansible.cli.adhoc as module_0

def test_case_0():
    try:
        float_0 = -2184.57111
        ad_hoc_c_l_i_0 = module_0.AdHocCLI(float_0)
        var_0 = ad_hoc_c_l_i_0.init_parser()
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'k6'
        ad_hoc_c_l_i_0 = module_0.AdHocCLI(str_0, str_0)
        var_0 = ad_hoc_c_l_i_0.run()
    except BaseException:
        pass