# Automatically generated by Pynguin.
import ansible.playbook.block as module_0
import ansible.playbook.role_include as module_1

def test_case_0():
    block_0 = module_0.Block()

def test_case_1():
    include_role_0 = module_1.IncludeRole()

def test_case_2():
    include_role_0 = module_1.IncludeRole()
    var_0 = include_role_0.get_name()

def test_case_3():
    str_0 = '5?c>SOc%U\tlbncVX\r'
    set_0 = {str_0, str_0, str_0}
    include_role_0 = module_1.IncludeRole()
    float_0 = -506.46
    include_role_1 = module_1.IncludeRole(include_role_0, float_0)
    var_0 = include_role_0.copy()
    float_1 = 3927.264772
    include_role_2 = module_1.IncludeRole(set_0, float_1)