# Automatically generated by Pynguin.
import ansible.plugins.callback.tree as module_0

def test_case_0():
    try:
        set_0 = set()
        float_0 = 3705.272
        callback_module_0 = module_0.CallbackModule(set_0, float_0)
    except BaseException:
        pass

def test_case_1():
    try:
        callback_module_0 = module_0.CallbackModule()
        var_0 = callback_module_0.write_tree_file(callback_module_0, callback_module_0)
    except BaseException:
        pass

def test_case_2():
    try:
        list_0 = []
        bool_0 = None
        callback_module_0 = module_0.CallbackModule()
        var_0 = callback_module_0.v2_runner_on_failed(list_0, bool_0)
    except BaseException:
        pass

def test_case_3():
    try:
        callback_module_0 = module_0.CallbackModule()
        int_0 = -414
        list_0 = [int_0, int_0]
        var_0 = callback_module_0.v2_runner_on_ok(list_0)
    except BaseException:
        pass

def test_case_4():
    try:
        callback_module_0 = module_0.CallbackModule()
        str_0 = 'Ljqq6$"y}%t&'
        var_0 = callback_module_0.v2_runner_on_unreachable(str_0)
    except BaseException:
        pass