# Automatically generated by Pynguin.
import sanic.blueprint_group as module_0
import sanic.blueprints as module_1

def test_case_0():
    pass

def test_case_1():
    blueprint_group_0 = module_0.BlueprintGroup()

def test_case_2():
    blueprint_group_0 = module_0.BlueprintGroup()
    str_0 = 'te'
    blueprint_0 = module_1.Blueprint(str_0, str_0)
    blueprint_group_0.append(blueprint_0)
    var_0 = blueprint_group_0.middleware()
    list_0 = [var_0]
    var_1 = blueprint_group_0.middleware(*list_0)

def test_case_3():
    str_0 = None
    blueprint_group_0 = None
    tuple_0 = (blueprint_group_0,)
    blueprint_0 = module_1.Blueprint(str_0, str_0, str_0, tuple_0)
    blueprint_group_1 = module_0.BlueprintGroup()
    blueprint_group_1.append(blueprint_0)

def test_case_4():
    str_0 = '/\x0c2{2\nP!ym?!7hu9'
    str_1 = 'p=~\tkG:5o'
    bytes_0 = b'\xb4\xdd"\x017\x85kC\x87\xc3\x131\xcas\x11E\x13l\xa1N'
    str_2 = '('
    dict_0 = {str_0: str_0, str_1: bytes_0, str_2: str_2}
    float_0 = 3213.0
    float_1 = -1531.48
    blueprint_group_0 = module_0.BlueprintGroup(float_0, float_1)
    var_0 = blueprint_group_0.middleware(**dict_0)
    bool_0 = False
    blueprint_group_1 = module_0.BlueprintGroup(bool_0)
    var_1 = blueprint_group_1.__iter__()

def test_case_5():
    blueprint_group_0 = module_0.BlueprintGroup()
    int_0 = blueprint_group_0.__len__()

def test_case_6():
    str_0 = 'test_app'
    list_0 = [str_0, str_0, str_0, str_0]
    blueprint_group_0 = module_0.BlueprintGroup()
    var_0 = blueprint_group_0.middleware(*list_0)