# Automatically generated by Pynguin.
import sanic.router as module_0

def test_case_0():
    try:
        str_0 = ' =neI~2kn0?Yq'
        router_0 = module_0.Router()
        float_0 = 699.2463
        float_1 = 15.0
        bool_0 = True
        bool_1 = False
        str_1 = 'Y"]:a`g\t7,[6BIRV~v['
        router_1 = module_0.Router(str_1)
        var_0 = router_1.add(str_0, float_0, float_1, str_0, str_0, str_0, bool_0, bool_1)
    except BaseException:
        pass

def test_case_1():
    try:
        router_0 = module_0.Router()
        var_0 = router_0.finalize()
    except BaseException:
        pass

def test_case_2():
    try:
        router_0 = module_0.Router()
        str_0 = '$yW,a\n1fq*cOb\r,}'
        str_1 = '\tFV%'
        dict_0 = {str_0: router_0, str_0: router_0, str_1: str_0}
        list_0 = [str_0, dict_0, router_0, str_0]
        callable_0 = None
        bool_0 = True
        var_0 = router_0.add(str_0, list_0, callable_0, bool_0, bool_0)
    except BaseException:
        pass