# Automatically generated by Pynguin.
import blib2to3.pgen2.grammar as module_0
import blib2to3.pgen2.parse as module_1

def test_case_0():
    grammar_0 = module_0.Grammar()

def test_case_1():
    str_0 = 'B'
    int_0 = 1057
    tuple_0 = None
    parse_error_0 = module_1.ParseError(str_0, int_0, str_0, tuple_0)