# Automatically generated by Pynguin.
import py_backwards.transformers.python2_future as module_0
import typed_ast._ast3 as module_1

def test_case_0():
    try:
        python2_future_transformer_0 = module_0.Python2FutureTransformer()
    except BaseException:
        pass

def test_case_1():
    try:
        module_x_var_0 = module_1.Module()
        a_s_t_0 = module_1.AST()
        python2_future_transformer_0 = module_0.Python2FutureTransformer(a_s_t_0)
        module_x_var_1 = python2_future_transformer_0.visit_Module(module_x_var_0)
    except BaseException:
        pass

def test_case_2():
    try:
        list_0 = []
        a_s_t_0 = module_1.AST(*list_0)
        list_1 = [a_s_t_0, a_s_t_0, list_0]
        list_2 = [list_1]
        module_x_var_0 = module_1.Module(*list_2)
        a_s_t_1 = module_1.AST()
        python2_future_transformer_0 = module_0.Python2FutureTransformer(a_s_t_1)
        module_x_var_1 = python2_future_transformer_0.visit_Module(module_x_var_0)
        a_s_t_2 = None
        python2_future_transformer_1 = module_0.Python2FutureTransformer(a_s_t_2)
        module_x_var_2 = module_1.Module()
        module_x_var_3 = python2_future_transformer_1.visit_Module(module_x_var_2)
    except BaseException:
        pass