# Automatically generated by Pynguin.
import ansible.executor.playbook_executor as module_0

def test_case_0():
    pass

def test_case_1():
    float_0 = -1921.7331719537565
    str_0 = 'No*y*wO>RP/\\b\x0bZ3}/v'
    playbook_executor_0 = module_0.PlaybookExecutor(str_0, float_0, float_0, str_0, str_0)