# Automatically generated by Pynguin.
import ansible.utils.singleton as module_0

def test_case_0():
    try:
        str_0 = 'Singleton'
        var_0 = ()
        var_1 = {}
        singleton_0 = module_0.Singleton(str_0, var_0, var_1)
        var_2 = singleton_0.__call__(str_0)
    except BaseException:
        pass