# Automatically generated by Pynguin.
import ansible.module_utils.compat.version as module_0

def test_case_0():
    try:
        str_0 = '@XY\tveP\\['
        loose_version_0 = module_0.LooseVersion(str_0)
        str_1 = '1.2.3'
        strict_version_0 = module_0.StrictVersion(str_1)
        var_0 = strict_version_0.__str__()
        var_1 = strict_version_0.__str__()
        list_0 = []
        version_0 = module_0.Version(list_0)
        var_2 = version_0.__repr__()
    except BaseException:
        pass

def test_case_1():
    try:
        list_0 = []
        version_0 = module_0.Version()
        var_0 = version_0.__eq__(list_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '1.2.3'
        strict_version_0 = module_0.StrictVersion(str_0)
        str_1 = ''
        var_0 = strict_version_0.__str__()
        version_0 = module_0.Version()
        var_1 = version_0.__lt__(str_1)
    except BaseException:
        pass

def test_case_3():
    try:
        tuple_0 = ()
        version_0 = module_0.Version()
        var_0 = version_0.__le__(tuple_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = '1.2.3'
        strict_version_0 = module_0.StrictVersion(str_0)
        var_0 = strict_version_0.__str__()
        version_0 = module_0.Version()
        str_1 = 'h\x0c D9uKza@_JbP-\n'
        var_1 = version_0.__ge__(str_1)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = '1.0'
        strict_version_0 = module_0.StrictVersion(str_0)
        str_1 = 'lg_esvn\rEv7d`wWXa'
        var_0 = strict_version_0.parse(str_1)
    except BaseException:
        pass

def test_case_6():
    try:
        loose_version_0 = module_0.LooseVersion()
        var_0 = loose_version_0.__repr__()
    except BaseException:
        pass

def test_case_7():
    try:
        version_0 = module_0.Version()
        int_0 = -620
        var_0 = version_0.__gt__(int_0)
    except BaseException:
        pass