# Automatically generated by Pynguin.
import ansible.plugins.lookup.file as module_0

def test_case_0():
    try:
        float_0 = 985.79706
        float_1 = 2372.0
        lookup_module_0 = module_0.LookupModule(float_1)
        var_0 = lookup_module_0.run(float_0)
    except BaseException:
        pass