# Automatically generated by Pynguin.
import tqdm.contrib.telegram as module_0

def test_case_0():
    pass

def test_case_1():
    tuple_0 = ()
    dict_0 = {tuple_0: tuple_0}
    telegram_i_o_0 = module_0.TelegramIO(tuple_0, dict_0)
    var_0 = telegram_i_o_0.delete()

def test_case_2():
    bytes_0 = b'}\x07r \xeb'
    tuple_0 = ()
    telegram_i_o_0 = module_0.TelegramIO(tuple_0, bytes_0)
    var_0 = telegram_i_o_0.delete()
    tqdm_telegram_0 = None
    var_1 = telegram_i_o_0.delete()
    var_2 = telegram_i_o_0.write(tqdm_telegram_0)
    str_0 = 'y%f;$VyI'
    var_3 = telegram_i_o_0.write(str_0)