# Automatically generated by Pynguin.
import ansible.parsing.utils.addresses as module_0

def test_case_0():
    str_0 = 'lsconf'
    var_0 = module_0.parse_address(str_0)

def test_case_1():
    str_0 = '192.168.1.1:80'
    var_0 = module_0.parse_address(str_0)
    str_1 = '[2001:db8::1]:80'
    var_1 = module_0.parse_address(str_1)
    var_2 = module_0.parse_address(str_0)
    str_2 = 'example.com:22'
    var_3 = module_0.parse_address(str_2)
    str_3 = 'example.com'
    var_4 = module_0.parse_address(str_3)