# Automatically generated by Pynguin.
import dataclasses_json.cfg as module_0

def test_case_0():
    try:
        str_0 = '2(5=\x0bDs|\\P!{CP4-'
        dict_0 = module_0.config(undefined=str_0, field_name=str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'required'
        list_0 = [str_0, str_0, str_0]
        optional_0 = None
        dict_0 = module_0.config(mm_field=list_0, letter_case=str_0, undefined=str_0, exclude=optional_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'g(=JjDka,`rq\rB@{'
        dict_0 = module_0.config(undefined=str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = '2(5S=Ds|\\P!&CP4'
        dict_0 = module_0.config(encoder=str_0, undefined=str_0, field_name=str_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'to'
        dict_0 = {str_0: str_0, str_0: str_0}
        dict_1 = module_0.config(dict_0, undefined=str_0)
    except BaseException:
        pass