# Automatically generated by Pynguin.
import ansible.plugins.lookup.csvfile as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = '9`\'AX2+b?ry"xM8D'
    c_s_v_recoder_0 = module_0.CSVRecoder(str_0)
    var_0 = c_s_v_recoder_0.__iter__()

def test_case_2():
    lookup_module_0 = None
    c_s_v_reader_0 = module_0.CSVReader(lookup_module_0)

def test_case_3():
    bytes_0 = b'\x0f:A<k\x1a\xa9(\x93\x91\xd5\xd9A9\xb5\xc4\x0e'
    dict_0 = {bytes_0: bytes_0, bytes_0: bytes_0}
    str_0 = '$ -m'
    dict_1 = {str_0: dict_0}
    lookup_module_0 = module_0.LookupModule(**dict_1)
    c_s_v_reader_0 = module_0.CSVReader(dict_0, lookup_module_0)
    var_0 = c_s_v_reader_0.__iter__()