# Automatically generated by Pynguin.
import tqdm.notebook as module_0

def test_case_0():
    try:
        tqdm_notebook_0 = module_0.tqdm_notebook()
    except BaseException:
        pass

def test_case_1():
    try:
        var_0 = module_0.tnrange()
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = "C293q\r\\~1K' "
        list_0 = [str_0, str_0, str_0]
        tqdm_notebook_0 = module_0.tqdm_notebook(*list_0)
    except BaseException:
        pass

def test_case_3():
    try:
        tqdm_notebook_0 = module_0.tqdm_notebook()
    except BaseException:
        pass

def test_case_4():
    try:
        tqdm_h_box_0 = module_0.TqdmHBox()
        var_0 = tqdm_h_box_0.__repr__()
        tqdm_h_box_1 = module_0.TqdmHBox()
        var_1 = tqdm_h_box_1.__repr__()
        var_2 = tqdm_h_box_1.__repr__()
        tqdm_notebook_0 = module_0.tqdm_notebook()
    except BaseException:
        pass

def test_case_5():
    try:
        int_0 = 10
        tqdm_notebook_0 = module_0.tqdm_notebook()
    except BaseException:
        pass