# Automatically generated by Pynguin.
import typesystem.fields as module_0

def test_case_0():
    pass

def test_case_1():
    date_0 = module_0.Date()

def test_case_2():
    str_0 = '$|+4y\t,}'
    choice_0 = module_0.Choice()
    boolean_0 = module_0.Boolean(title=str_0, description=str_0, default=choice_0)

def test_case_3():
    field_0 = module_0.Field()
    any_0 = field_0.serialize(field_0)
    any_1 = field_0.get_default_value()

def test_case_4():
    bool_0 = True
    string_0 = module_0.String(allow_blank=bool_0, trim_whitespace=bool_0)

def test_case_5():
    field_0 = module_0.Field()
    any_0 = field_0.get_default_value()

def test_case_6():
    field_0 = module_0.Field()
    union_0 = field_0.__or__(field_0)

def test_case_7():
    string_0 = module_0.String()
    any_0 = string_0.serialize(string_0)

def test_case_8():
    decimal_0 = module_0.Decimal()

def test_case_9():
    float_0 = 3894.8673594404577
    number_0 = module_0.Number(multiple_of=float_0)
    any_0 = number_0.validate(float_0)

def test_case_10():
    choice_0 = module_0.Choice()

def test_case_11():
    object_0 = module_0.Object()

def test_case_12():
    field_0 = module_0.Field()
    object_0 = module_0.Object(additional_properties=field_0, property_names=field_0)

def test_case_13():
    list_0 = []
    bool_0 = False
    array_0 = module_0.Array(list_0, bool_0)

def test_case_14():
    array_0 = module_0.Array()

def test_case_15():
    field_0 = module_0.Field()
    int_0 = -2566
    array_0 = module_0.Array(field_0, field_0, int_0, int_0)

def test_case_16():
    list_0 = []
    array_0 = module_0.Array()
    any_0 = array_0.validate(list_0)

def test_case_17():
    text_0 = module_0.Text()

def test_case_18():
    time_0 = module_0.Time()

def test_case_19():
    date_time_0 = module_0.DateTime()

def test_case_20():
    date_0 = module_0.Date()
    bool_0 = True
    field_0 = module_0.Field(allow_null=bool_0)
    list_0 = [field_0, field_0]
    union_0 = module_0.Union(list_0)

def test_case_21():
    choice_0 = module_0.Choice()
    bool_0 = True
    field_0 = module_0.Field(default=choice_0, allow_null=bool_0)
    any_0 = field_0.get_default_value()

def test_case_22():
    string_0 = module_0.String()

def test_case_23():
    float_0 = 763.0
    number_0 = module_0.Number(minimum=float_0, multiple_of=float_0)
    any_0 = number_0.validate(float_0)

def test_case_24():
    dict_0 = {}
    field_0 = module_0.Field()
    int_0 = 1036
    object_0 = module_0.Object(max_properties=int_0)
    any_0 = object_0.validate(dict_0)

def test_case_25():
    int_0 = -1409
    string_0 = module_0.String(max_length=int_0, min_length=int_0)

def test_case_26():
    int_0 = 10
    string_0 = module_0.String(min_length=int_0)

def test_case_27():
    array_0 = module_0.Array()
    string_0 = module_0.String()
    any_0 = array_0.serialize(string_0)

def test_case_28():
    dict_0 = {}
    field_0 = module_0.Field()
    object_0 = module_0.Object(additional_properties=field_0, property_names=field_0)
    any_0 = object_0.validate(dict_0)

def test_case_29():
    bytes_0 = b'\xdab\xc2\x14\xd2\xca\xbf4\x86iXV\x11\xabA\xd5'
    choice_0 = module_0.Choice(choices=bytes_0)

def test_case_30():
    bool_0 = True
    bool_1 = False
    boolean_0 = module_0.Boolean(default=bool_0, allow_null=bool_1)
    any_0 = boolean_0.validate(bool_0, strict=bool_0)

def test_case_31():
    str_0 = 'D'
    string_0 = module_0.String()
    any_0 = string_0.validate(str_0)

def test_case_32():
    str_0 = 'O2w7q^'
    bool_0 = True
    int_0 = 552
    dict_0 = {}
    string_0 = module_0.String(max_length=int_0, min_length=int_0, format=str_0)
    any_0 = module_0.Any()
    string_1 = module_0.String(trim_whitespace=bool_0, max_length=int_0, **dict_0)
    any_1 = string_1.validate(str_0)

def test_case_33():
    bool_0 = True
    string_0 = module_0.String(allow_blank=bool_0, trim_whitespace=bool_0)
    str_0 = '@!BiFSZu9'
    field_0 = module_0.Field(description=str_0)
    bool_1 = True
    any_0 = string_0.validate(str_0, strict=bool_1)

def test_case_34():
    dict_0 = {}
    field_0 = module_0.Field()
    array_0 = module_0.Array(field_0)
    any_0 = array_0.serialize(dict_0)
    choice_0 = module_0.Choice()

def test_case_35():
    str_0 = '1Qqy\x0cy`VfANUysp\n\n'
    list_0 = [str_0, str_0, str_0]
    array_0 = module_0.Array()
    any_0 = array_0.validate(list_0)

def test_case_36():
    str_0 = '\rfurDrXO+;]Scq&'
    bool_0 = False
    list_0 = [str_0]
    choice_0 = module_0.Choice(choices=list_0)
    any_0 = choice_0.validate(str_0, strict=bool_0)

def test_case_37():
    str_0 = ''
    dict_0 = {str_0: str_0}
    object_0 = module_0.Object()
    any_0 = object_0.validate(dict_0)

def test_case_38():
    float_0 = 3896.0
    number_0 = module_0.Number()
    any_0 = number_0.validate(float_0)

def test_case_39():
    str_0 = 'templates'
    field_0 = module_0.Field(description=str_0)
    int_0 = 4
    bool_0 = False
    array_0 = module_0.Array(field_0, field_0, int_0, int_0, int_0, bool_0)
    string_0 = module_0.String(max_length=int_0)

def test_case_40():
    list_0 = []
    bool_0 = True
    array_0 = module_0.Array(list_0, bool_0)

def test_case_41():
    choice_0 = module_0.Choice()
    str_0 = 'May not be null.'
    field_0 = module_0.Field(description=str_0)
    bool_0 = field_0.has_default()
    bool_1 = True
    bool_2 = None
    int_0 = 27
    string_0 = module_0.String(allow_blank=bool_1, trim_whitespace=bool_2, max_length=int_0)
    any_0 = string_0.validate(bool_2)

def test_case_42():
    choice_0 = module_0.Choice()
    str_0 = 'Krs\nBvSN;AT"_;&%'
    field_0 = module_0.Field(default=choice_0)
    dict_0 = {str_0: field_0, str_0: field_0, str_0: field_0}
    sequence_0 = None
    dict_1 = {}
    object_0 = module_0.Object(properties=dict_0, required=sequence_0, **dict_1)
    any_0 = object_0.validate(dict_1)

def test_case_43():
    int_0 = 2752
    number_0 = module_0.Number(minimum=int_0, exclusive_maximum=int_0)
    int_1 = 1036
    dict_0 = {}
    str_0 = 'C_O'
    str_1 = 'f\x0b'
    field_0 = module_0.Field(description=str_1, default=int_1)
    str_2 = '?'
    dict_1 = {str_0: field_0, str_2: field_0}
    str_3 = ';'
    str_4 = 'Ay:\x0b`.\teVT-!j2op-bW8'
    dict_2 = {str_3: field_0, str_4: field_0, str_1: field_0, str_1: field_0}
    object_0 = module_0.Object(properties=dict_1, pattern_properties=dict_2, property_names=field_0)
    any_0 = object_0.validate(dict_0)

def test_case_44():
    int_0 = -1409
    int_1 = None
    number_0 = module_0.Number(maximum=int_0, exclusive_minimum=int_1, multiple_of=int_0)
    any_0 = number_0.validate(int_0)

def test_case_45():
    dict_0 = {}
    field_0 = module_0.Field()
    field_1 = None
    object_0 = module_0.Object(additional_properties=field_1, property_names=field_0, **dict_0)
    any_0 = object_0.validate(dict_0)

def test_case_46():
    str_0 = 'Field 1'
    field_0 = module_0.Field(title=str_0)
    str_1 = 'Field 2'
    field_1 = module_0.Field(title=str_1)
    var_0 = field_0 | field_1
    var_1 = var_0.any_of
    var_2 = len(var_1)
    str_2 = 'Field 3'
    field_2 = module_0.Field(title=str_2)
    var_3 = field_0 | field_1
    var_4 = var_3 | field_2

def test_case_47():
    field_0 = module_0.Field()
    field_1 = module_0.Field()
    field_2 = [field_0, field_1]
    array_0 = module_0.Array(field_2)
    int_0 = 123
    str_0 = 'test'
    var_0 = [int_0, str_0]
    any_0 = array_0.serialize(var_0)
    var_1 = None
    any_1 = array_0.serialize(var_1)
    field_3 = module_0.Field()
    array_1 = module_0.Array(field_3)
    int_1 = 1
    int_2 = 2
    int_3 = 3
    int_4 = [int_1, int_2, int_3]
    any_2 = array_1.serialize(int_4)

def test_case_48():
    field_0 = module_0.Field()
    list_0 = None
    bool_0 = True
    boolean_0 = module_0.Boolean(allow_null=bool_0)
    any_0 = boolean_0.validate(list_0, strict=bool_0)

def test_case_49():
    choice_0 = module_0.Choice()
    choice_1 = None
    bool_0 = True
    str_0 = 'S4I2kRhOWQ&n]'
    field_0 = module_0.Field(title=str_0)
    bool_1 = True
    field_1 = module_0.Field(allow_null=bool_1)
    list_0 = [field_0, field_0, field_1, field_1]
    union_0 = module_0.Union(list_0)
    any_0 = union_0.validate(choice_1, bool_0)

def test_case_50():
    list_0 = []
    dict_0 = {}
    array_0 = module_0.Array(list_0, **dict_0)
    any_0 = array_0.validate(list_0)

def test_case_51():
    float_0 = 2167.58923
    number_0 = module_0.Number(maximum=float_0, exclusive_maximum=float_0)
    number_1 = module_0.Number()
    int_0 = -2621
    bool_0 = False
    any_0 = number_0.validate(int_0, strict=bool_0)

def test_case_52():
    str_0 = ''
    bool_0 = True
    boolean_0 = module_0.Boolean(allow_null=bool_0)
    any_0 = boolean_0.validate(str_0)