# Automatically generated by Pynguin.
import ansible.modules.pip as module_0

def test_case_0():
    try:
        int_0 = 5301
        str_0 = 'x}cnnI4<Q%5YG+Cb5<'
        float_0 = -2033.7474
        set_0 = None
        dict_0 = {str_0: float_0, set_0: float_0}
        var_0 = module_0.setup_virtualenv(int_0, str_0, float_0, set_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = 2378
        package_0 = module_0.Package(int_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = 'example'
        package_0 = module_0.Package(str_0)
        float_0 = -705.604802
        var_0 = package_0.is_satisfied_by(float_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'exmtle'
        package_0 = module_0.Package(str_0)
        var_0 = package_0.is_satisfied_by(str_0)
        package_1 = module_0.Package(str_0, str_0)
        str_1 = '?@X\n_zHA_&c:-Q'
        var_1 = package_0.is_satisfied_by(str_1)
        int_0 = 32600
        tuple_0 = (int_0,)
        var_2 = package_1.is_satisfied_by(tuple_0)
        package_2 = module_0.Package(package_1)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'distribute'
        package_0 = module_0.Package(str_0)
        var_0 = package_0.is_satisfied_by(package_0)
    except BaseException:
        pass