# Automatically generated by Pynguin.
import ansible.utils.context_objects as module_0

def test_case_0():
    try:
        str_0 = 'Could not modify override file'
        list_0 = [str_0]
        bool_0 = None
        tuple_0 = (list_0, list_0, bool_0)
        int_0 = 962
        dict_0 = {str_0: tuple_0, int_0: bool_0}
        c_l_i_args_0 = module_0.CLIArgs(dict_0)
        bytes_0 = b'L'
        a_b_c_singleton_0 = module_0._ABCSingleton(c_l_i_args_0, bytes_0, int_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        bool_0 = True
        global_c_l_i_args_0 = None
        int_0 = 203
        dict_0 = {bool_0: global_c_l_i_args_0, global_c_l_i_args_0: int_0}
        c_l_i_args_0 = module_0.CLIArgs(dict_0)
        tuple_0 = (c_l_i_args_0, c_l_i_args_0, c_l_i_args_0)
        a_b_c_singleton_0 = module_0._ABCSingleton(global_c_l_i_args_0, int_0, dict_0, tuple_0)
    except BaseException:
        pass

def test_case_2():
    try:
        global_c_l_i_args_0 = None
        c_l_i_args_0 = module_0.CLIArgs(global_c_l_i_args_0)
    except BaseException:
        pass