# Automatically generated by Pynguin.
import ansible.utils.context_objects as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = 'simple'
    str_1 = 'list'
    str_2 = 'dict'
    str_3 = 'set'
    str_4 = 'nested'
    str_5 = 'value'
    int_0 = 1
    int_1 = 2
    int_2 = 3
    int_3 = [int_0, int_1, int_2]
    str_6 = 'a'
    str_7 = 'b'
    int_4 = {str_6: int_0, str_7: int_1}
    int_5 = {int_0, int_1, int_2}
    int_6 = {str_6: int_2, str_7: int_3}
    var_0 = {str_0: str_5, str_1: int_3, str_2: int_4, str_3: int_5, str_4: int_6}
    c_l_i_args_0 = module_0.CLIArgs(var_0)
    var_1 = c_l_i_args_0[str_1]
    var_2 = c_l_i_args_0[str_2]
    var_3 = c_l_i_args_0[str_3]
    var_4 = c_l_i_args_0[str_4]
    var_5 = c_l_i_args_0[str_4][str_6]

def test_case_2():
    str_0 = 'simple_key'
    str_1 = 'nested_dict'
    str_2 = 'simple_list'
    str_3 = 'simple_value'
    str_4 = 'inner_key'
    str_5 = 'inner_value'
    var_0 = {str_4: str_5}
    str_6 = 'a'
    str_7 = 'b'
    str_8 = 'c'
    str_9 = [str_6, str_7, str_8]
    str_10 = 'Q'
    str_11 = 'y'
    str_12 = 'z'
    str_13 = {str_10, str_11, str_12}
    var_1 = {str_0: str_3, str_1: var_0, str_2: str_9, str_2: str_13}
    c_l_i_args_0 = module_0.CLIArgs(var_1)