# Automatically generated by Pynguin.
import tornado.options as module_0
import builtins as module_1

def test_case_0():
    pass

def test_case_1():
    module_0.print_help()
    option_parser_0 = module_0.OptionParser()
    set_0 = option_parser_0.groups()
    dict_0 = option_parser_0.as_dict()

def test_case_2():
    module_0.print_help()
    str_0 = '%78,EyR'
    module_0.define(str_0, str_0, str_0)

def test_case_3():
    str_0 = '/input/tornado/options.py'
    option_parser_0 = module_0.OptionParser()
    iterator_0 = option_parser_0.__iter__()
    bool_0 = True
    option_parser_0.parse_config_file(str_0, bool_0)
    dict_0 = option_parser_0.as_dict()

def test_case_4():
    module_0.print_help()

def test_case_5():
    option_parser_0 = module_0.OptionParser()
    option_parser_0.run_parse_callbacks()

def test_case_6():
    option_parser_0 = module_0.OptionParser()
    mockable_0 = option_parser_0.mockable()

def test_case_7():
    str_0 = 'ZDs\n#f"'
    set_0 = {str_0, str_0}
    list_0 = [set_0]
    type_0 = module_1.type(*list_0)
    option_0 = module_0._Option(str_0, str_0, type_0, str_0)
    any_0 = option_0.parse(str_0)

def test_case_8():
    str_0 = 'ZDs\n#f"'
    set_0 = {str_0, str_0, str_0, str_0, str_0}
    list_0 = [set_0]
    type_0 = module_1.type(*list_0)
    option_0 = module_0._Option(str_0, str_0, type_0, str_0)
    option_0.set(set_0)

def test_case_9():
    str_0 = '/fH?/\x0coWV{nqqk\r3xc'
    option_parser_0 = module_0.OptionParser()
    list_0 = [str_0]
    type_0 = module_1.type(*list_0)
    option_0 = module_0._Option(str_0, str_0, type_0, str_0)
    dict_0 = option_parser_0.group_dict(str_0)
    str_1 = '_handle_event'
    option_parser_0.print_help()
    float_0 = 3938.64148
    option_1 = module_0._Option(str_1, option_parser_0, type_0, str_1, str_1, str_0, float_0)
    any_0 = option_1.parse(str_0)