# Automatically generated by Pynguin.
import ansible.modules.pip as module_0

def test_case_0():
    try:
        str_0 = 'iK!_d'
        package_0 = module_0.Package(str_0)
        bool_0 = True
        set_0 = {str_0, package_0, bool_0, package_0}
        var_0 = package_0.is_satisfied_by(set_0)
        var_1 = package_0.is_satisfied_by(bool_0)
        var_2 = package_0.__str__()
        float_0 = None
        int_0 = -469
        var_3 = module_0.setup_virtualenv(float_0, str_0, set_0, int_0, bool_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '2.18.4'
        package_0 = module_0.Package(str_0, str_0)
        var_0 = package_0.is_satisfied_by(package_0)
    except BaseException:
        pass

def test_case_2():
    try:
        float_0 = 991.0
        package_0 = module_0.Package(float_0)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'oU-'
        float_0 = 2.0
        package_0 = module_0.Package(str_0, float_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'BV#X7f|'
        package_0 = module_0.Package(str_0)
        bool_0 = False
        var_0 = package_0.is_satisfied_by(bool_0)
        list_0 = [package_0]
        var_1 = package_0.canonicalize_name(list_0)
    except BaseException:
        pass

def test_case_5():
    try:
        bytes_0 = b'\xfe\xe8>'
        str_0 = ',-Tv?2aI5W'
        package_0 = module_0.Package(bytes_0, str_0)
    except BaseException:
        pass