# Automatically generated by Pynguin.
import httpie.cli.argparser as module_0
import httpie.context as module_1

def test_case_0():
    try:
        h_t_t_pie_help_formatter_0 = module_0.HTTPieHelpFormatter()
    except BaseException:
        pass

def test_case_1():
    try:
        environment_0 = module_1.Environment()
        h_t_t_pie_argument_parser_0 = module_0.HTTPieArgumentParser()
        namespace_0 = h_t_t_pie_argument_parser_0.parse_args(environment_0)
    except BaseException:
        pass