# Automatically generated by Pynguin.
import youtube_dl.postprocessor.xattrpp as module_0

def test_case_0():
    try:
        x_attr_metadata_p_p_0 = module_0.XAttrMetadataPP()
        tuple_0 = ()
        x_attr_metadata_p_p_1 = module_0.XAttrMetadataPP(tuple_0)
        var_0 = x_attr_metadata_p_p_1.run(x_attr_metadata_p_p_0)
    except BaseException:
        pass