# Automatically generated by Pynguin.
import httpie.sessions as module_0
import pathlib as module_1
import httpie.cli.dicts as module_2

def test_case_0():
    try:
        path_0 = None
        session_0 = module_0.Session(path_0)
    except BaseException:
        pass

def test_case_1():
    try:
        path_0 = module_1.Path()
        str_0 = 'tM%/Vr'
        str_1 = '\r:XygM\\8_0\\wy'
        session_0 = module_0.get_httpie_session(path_0, str_0, str_0, str_1)
        str_2 = 'VS3a'
        dict_0 = {str_2: str_2, str_2: str_2}
        request_headers_dict_0 = module_2.RequestHeadersDict(**dict_0)
        path_1 = module_1.Path()
        session_1 = module_0.get_httpie_session(path_1, str_2, str_2, str_2)
        var_0 = session_1.update_headers(request_headers_dict_0)
        str_3 = '=\rfft^Ok'
        session_2 = module_0.Session(path_1)
        session_3 = module_0.get_httpie_session(path_1, str_3, str_3, str_3)
        var_1 = session_3.update_headers(request_headers_dict_0)
        str_4 = '.'
        var_2 = session_3.remove_cookies(str_4)
        var_3 = session_3.update_headers(request_headers_dict_0)
        str_5 = 'Rv&\r/yE.'
        tuple_0 = (str_5,)
        var_4 = path_1.link_to(tuple_0)
    except BaseException:
        pass

def test_case_2():
    try:
        path_0 = module_1.Path()
        str_0 = None
        session_0 = module_0.get_httpie_session(path_0, str_0, str_0, str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        path_0 = module_1.Path()
        session_0 = module_0.Session(path_0)
        request_headers_dict_0 = module_2.RequestHeadersDict(session_0)
        path_1 = module_1.Path()
        session_1 = module_0.Session(path_1)
        var_0 = session_1.update_headers(request_headers_dict_0)
    except BaseException:
        pass