# Automatically generated by Pynguin.
import ansible.playbook.playbook_include as module_0

def test_case_0():
    try:
        dict_0 = {}
        playbook_include_0 = module_0.PlaybookInclude()
        var_0 = playbook_include_0.load(dict_0, dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = 2270.0
        playbook_include_0 = module_0.PlaybookInclude()
        var_0 = playbook_include_0.preprocess_data(float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        dict_0 = {}
        playbook_include_1 = module_0.PlaybookInclude()
        int_0 = 2269
        var_0 = playbook_include_0.load_data(dict_0, playbook_include_1, int_0)
    except BaseException:
        pass

def test_case_3():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        str_0 = 'R[<D'
        dict_0 = {playbook_include_0: playbook_include_0, playbook_include_0: playbook_include_0, str_0: str_0, str_0: playbook_include_0}
        var_0 = playbook_include_0.preprocess_data(dict_0)
        playbook_include_1 = module_0.PlaybookInclude()
        playbook_include_2 = module_0.PlaybookInclude()
        bytes_0 = b'\xab\x1d\xb5`\x839m\xb3}\x12*\xba\xaa2{'
        var_1 = playbook_include_1.load_data(var_0, bytes_0, playbook_include_1)
    except BaseException:
        pass

def test_case_4():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        str_0 = 'some_playbook.yml'
        str_1 = 'vars'
        str_2 = 'my_var'
        str_3 = {str_2: str_0, str_1: str_0}
        var_0 = playbook_include_0.preprocess_data(str_3)
    except BaseException:
        pass

def test_case_5():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        str_0 = 'import_playbook'
        str_1 = {str_0: str_0, str_0: str_0, str_0: playbook_include_0}
        var_0 = playbook_include_0.preprocess_data(str_1)
    except BaseException:
        pass

def test_case_6():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        str_0 = 'import_playbook'
        str_1 = 'p7ugin redirect loop resolving {0} (path: {1})'
        str_2 = 'vars'
        str_3 = {str_0: str_1, str_2: str_1}
        var_0 = playbook_include_0.preprocess_data(str_3)
    except BaseException:
        pass

def test_case_7():
    try:
        playbook_include_0 = module_0.PlaybookInclude()
        str_0 = 'import_playbook'
        str_1 = ''
        dict_0 = {str_0: str_1, str_1: playbook_include_0, str_0: str_0}
        var_0 = playbook_include_0.preprocess_data(dict_0)
        str_2 = {str_0: str_1, str_0: str_1}
        var_1 = playbook_include_0.preprocess_data(str_2)
    except BaseException:
        pass