# Automatically generated by Pynguin.
import mimesis.enums as module_0
import mimesis.providers.internet as module_1

def test_case_0():
    try:
        t_l_d_type_0 = module_0.TLDType.GTLD
        list_0 = [t_l_d_type_0, t_l_d_type_0, t_l_d_type_0, t_l_d_type_0]
        internet_0 = module_1.Internet()
        str_0 = internet_0.http_status_message()
        dict_0 = {}
        internet_1 = module_1.Internet(*list_0, **dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        internet_0 = module_1.Internet()
        str_0 = internet_0.user_agent()
        list_0 = []
        internet_1 = module_1.Internet(*list_0)
        str_1 = internet_1.content_type()
        str_2 = internet_1.mac_address()
        float_0 = 45.579876
        internet_2 = module_1.Internet(*list_0)
        int_0 = internet_1.http_status_code()
        int_1 = internet_2.port()
        str_3 = internet_2.content_type(float_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '4"i%VT @ &ZZ._mr&as'
        list_0 = [str_0, str_0, str_0]
        internet_0 = module_1.Internet()
        str_1 = internet_0.emoji()
        bool_0 = True
        i_pv4_address_0 = internet_0.ip_v4_object()
        var_0 = internet_0.stock_image(str_1, str_1, list_0, bool_0)
    except BaseException:
        pass

def test_case_3():
    try:
        float_0 = None
        internet_0 = module_1.Internet()
        str_0 = internet_0.home_page()
        list_0 = [float_0, float_0]
        str_1 = "v%'^\\x%n/\r"
        internet_1 = module_1.Internet()
        str_2 = internet_0.network_protocol()
        str_3 = internet_1.image_placeholder(str_1)
        str_4 = internet_1.ip_v6()
        internet_2 = module_1.Internet(*list_0)
    except BaseException:
        pass

def test_case_4():
    try:
        str_0 = 'RUS'
        list_0 = [str_0, str_0, str_0]
        internet_0 = module_1.Internet()
        str_1 = internet_0.image_placeholder(str_0)
        bool_0 = True
        i_pv4_address_0 = internet_0.ip_v4_object()
        var_0 = internet_0.stock_image(str_0, str_1, list_0, bool_0)
    except BaseException:
        pass

def test_case_5():
    try:
        internet_0 = module_1.Internet()
        str_0 = internet_0.home_page()
        str_1 = internet_0.mac_address()
        i_pv6_address_0 = internet_0.ip_v6_object()
        int_0 = internet_0.port()
        port_range_0 = None
        int_1 = internet_0.port()
        str_2 = internet_0.image_placeholder(int_0)
        var_0 = internet_0.stock_image(port_range_0)
        int_2 = internet_0.port()
        str_3 = internet_0.ip_v4()
        str_4 = internet_0.ip_v4()
        int_3 = internet_0.port(port_range_0)
    except BaseException:
        pass