# Automatically generated by Pynguin.
import ansible.plugins.filter.urls as module_0

def test_case_0():
    filter_module_0 = module_0.FilterModule()

def test_case_1():
    str_0 = 'PolSp;_SP'
    var_0 = module_0.unicode_urlencode(str_0)

def test_case_2():
    filter_module_0 = module_0.FilterModule()
    var_0 = filter_module_0.filters()

def test_case_3():
    str_0 = 'Invalid role name (%s). Specify role as format: username.rolename'
    var_0 = module_0.do_urlencode(str_0)

def test_case_4():
    list_0 = []
    var_0 = module_0.do_urlencode(list_0)
    str_0 = 'Request failed'
    var_1 = module_0.do_urlencode(str_0)
    filter_module_0 = module_0.FilterModule()
    var_2 = filter_module_0.filters()