# Automatically generated by Pynguin.
import ansible.module_utils.facts.hardware.hpux as module_0

def test_case_0():
    try:
        str_0 = '#m%=wWL'
        h_p_u_x_hardware_0 = module_0.HPUXHardware(str_0)
        var_0 = h_p_u_x_hardware_0.populate()
    except BaseException:
        pass

def test_case_1():
    try:
        bool_0 = False
        str_0 = '\x0cC6r=-'
        h_p_u_x_hardware_0 = module_0.HPUXHardware(bool_0, str_0)
        var_0 = h_p_u_x_hardware_0.get_hw_facts()
    except BaseException:
        pass

def test_case_2():
    try:
        bool_0 = True
        h_p_u_x_hardware_0 = None
        dict_0 = {h_p_u_x_hardware_0: h_p_u_x_hardware_0, h_p_u_x_hardware_0: h_p_u_x_hardware_0, h_p_u_x_hardware_0: h_p_u_x_hardware_0}
        h_p_u_x_hardware_1 = module_0.HPUXHardware(dict_0)
        var_0 = h_p_u_x_hardware_1.populate(bool_0)
    except BaseException:
        pass

def test_case_3():
    try:
        bytes_0 = b'\xc2\x85$[R\t\xfa\x1a\xe6t$\xa4#'
        bytes_1 = b'\xd9\xe4K\xe8\xeb\xdcDn\xf4\xe1\xe2\xcb\x94(&l\xd6'
        h_p_u_x_hardware_0 = module_0.HPUXHardware(bytes_1)
        var_0 = h_p_u_x_hardware_0.get_memory_facts(bytes_0)
    except BaseException:
        pass

def test_case_4():
    try:
        h_p_u_x_hardware_collector_0 = module_0.HPUXHardwareCollector()
        h_p_u_x_hardware_0 = module_0.HPUXHardware(h_p_u_x_hardware_collector_0)
        set_0 = set()
        h_p_u_x_hardware_1 = module_0.HPUXHardware(set_0)
        var_0 = h_p_u_x_hardware_1.get_hw_facts(h_p_u_x_hardware_0)
    except BaseException:
        pass