# Automatically generated by Pynguin.
import httpie.output.streams as module_0
import httpie.models as module_1

def test_case_0():
    pass

def test_case_1():
    h_t_t_p_message_0 = None
    base_stream_0 = module_0.BaseStream(h_t_t_p_message_0, h_t_t_p_message_0)

def test_case_2():
    data_suppressed_error_0 = module_0.DataSuppressedError()
    h_t_t_p_message_0 = module_1.HTTPMessage(data_suppressed_error_0)
    base_stream_0 = module_0.BaseStream(h_t_t_p_message_0)