# Automatically generated by Pynguin.
import ansible.vars.hostvars as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = "i}u4'EUnD{"
    list_0 = [str_0]
    host_vars_vars_0 = module_0.HostVarsVars(list_0, str_0)

def test_case_2():
    tuple_0 = ()
    set_0 = None
    str_0 = "}02QA*Ma'@I#2"
    dict_0 = {}
    host_vars_vars_0 = module_0.HostVarsVars(set_0, dict_0)
    float_0 = None
    tuple_1 = (dict_0, float_0)
    list_0 = [float_0]
    host_vars_vars_1 = module_0.HostVarsVars(tuple_1, list_0)
    list_1 = [tuple_0, str_0]
    bytes_0 = b'M\xe9\xc8&\xbe\x18\x9c\x95\xa0\xf3\x8c\xcdy\xa5m=\x9aa\xba\x91'
    host_vars_vars_2 = module_0.HostVarsVars(list_1, bytes_0)
    bool_0 = True
    host_vars_vars_3 = module_0.HostVarsVars(str_0, bool_0)
    host_vars_0 = module_0.HostVars(host_vars_vars_2, host_vars_vars_0, tuple_1)
    var_0 = host_vars_0.__setstate__(dict_0)
    var_1 = host_vars_vars_2.__contains__(host_vars_vars_1)

def test_case_3():
    tuple_0 = ()
    float_0 = 0.5
    set_0 = None
    set_1 = {float_0, set_0}
    str_0 = "}02QA*Ma'@I#2"
    host_vars_vars_0 = module_0.HostVarsVars(set_1, str_0)
    host_vars_0 = module_0.HostVars(float_0, host_vars_vars_0, set_1)
    var_0 = host_vars_0.__deepcopy__(tuple_0)

def test_case_4():
    set_0 = None
    dict_0 = {}
    host_vars_vars_0 = module_0.HostVarsVars(set_0, dict_0)
    float_0 = None
    tuple_0 = (dict_0, float_0)
    host_vars_0 = module_0.HostVars(host_vars_vars_0, host_vars_vars_0, tuple_0)
    var_0 = host_vars_0.__setstate__(dict_0)

def test_case_5():
    tuple_0 = ()
    float_0 = 0.5
    set_0 = None
    set_1 = {float_0, set_0}
    str_0 = "}02QA*Ma'@I#2"
    host_vars_vars_0 = module_0.HostVarsVars(set_1, str_0)
    host_vars_0 = module_0.HostVars(float_0, host_vars_vars_0, set_1)
    var_0 = host_vars_0.__deepcopy__(tuple_0)
    bool_0 = True
    var_1 = host_vars_0.set_inventory(bool_0)

def test_case_6():
    float_0 = -2076.26
    dict_0 = {float_0: float_0}
    host_vars_vars_0 = module_0.HostVarsVars(float_0, dict_0)
    tuple_0 = ()
    set_0 = None
    str_0 = "}02QA*Ma'@I#2"
    dict_1 = {}
    host_vars_vars_1 = module_0.HostVarsVars(set_0, dict_1)
    var_0 = host_vars_vars_1.__repr__()
    dict_2 = {tuple_0: set_0, set_0: host_vars_vars_1}
    float_1 = None
    tuple_1 = (dict_2, float_1)
    list_0 = [float_1]
    host_vars_vars_2 = module_0.HostVarsVars(tuple_1, list_0)
    list_1 = [tuple_0, str_0]
    bytes_0 = b'M\xe9\xc8&\xbe\x18\x9c\x95\xa0\xf3\x8c\xcdy\xa5m=\x9aa\xba\x91'
    host_vars_vars_3 = module_0.HostVarsVars(list_1, bytes_0)
    str_1 = 'sha1'
    bool_0 = True
    host_vars_vars_4 = module_0.HostVarsVars(str_1, bool_0)
    host_vars_0 = module_0.HostVars(host_vars_vars_3, host_vars_vars_1, tuple_1)
    int_0 = 1292
    var_1 = host_vars_0.__deepcopy__(int_0)
    str_2 = '$qynQwSx\nm'
    var_2 = host_vars_vars_2.__contains__(str_2)
    host_vars_vars_5 = module_0.HostVarsVars(dict_1, dict_2)
    var_3 = host_vars_vars_2.__contains__(host_vars_vars_5)