# Automatically generated by Pynguin.
import thefuck.argument_parser as module_0

def test_case_0():
    try:
        parser_0 = module_0.Parser()
        str_0 = 's6a;?@QTHs6yk_{L'
        var_0 = parser_0.parse(str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = "pnwl{p:i[760'p)JU:kw"
        float_0 = 0.1
        parser_0 = module_0.Parser()
        var_0 = parser_0.print_usage()
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0, float_0: float_0}
        tuple_0 = (dict_0,)
        parser_1 = module_0.Parser()
        parser_2 = module_0.Parser()
        var_1 = parser_2.parse(tuple_0)
        parser_3 = module_0.Parser()
        str_1 = '8IAl/Hqy,'
        var_2 = parser_3.parse(str_1)
    except BaseException:
        pass