# Automatically generated by Pynguin.
import py_backwards.transformers.yield_from as module_0

def test_case_0():
    try:
        yield_from_transformer_0 = module_0.YieldFromTransformer()
    except BaseException:
        pass