# Automatically generated by Pynguin.
import ansible.parsing.yaml.dumper as module_0

def test_case_0():
    try:
        ansible_dumper_0 = module_0.AnsibleDumper()
    except BaseException:
        pass