# Automatically generated by Pynguin.
import ansible.executor.process.worker as module_0

def test_case_0():
    try:
        str_0 = '%s:'
        dict_0 = {str_0: str_0, str_0: str_0, str_0: str_0}
        set_0 = {str_0}
        int_0 = 352
        worker_process_0 = module_0.WorkerProcess(str_0, str_0, str_0, dict_0, set_0, set_0, str_0, int_0)
    except BaseException:
        pass