# Automatically generated by Pynguin.
import ansible.template.native_helpers as module_0

def test_case_0():
    str_0 = 'hXlLU-&k2h#u5G3'
    var_0 = module_0.ansible_native_concat(str_0)

def test_case_1():
    bytes_0 = b'\x9c\x9fD'
    int_0 = 1821
    dict_0 = {bytes_0: bytes_0, bytes_0: int_0}
    var_0 = module_0.ansible_native_concat(dict_0)
    dict_1 = {bytes_0: bytes_0}
    str_0 = "h>6.K?V'"
    tuple_0 = (bytes_0, dict_1, str_0)
    var_1 = module_0.ansible_native_concat(tuple_0)
    var_2 = module_0.ansible_native_concat(bytes_0)

def test_case_2():
    str_0 = '\\'
    var_0 = module_0.ansible_native_concat(str_0)

def test_case_3():
    bytes_0 = b'\xa3'
    var_0 = module_0.ansible_native_concat(bytes_0)

def test_case_4():
    str_0 = ''
    var_0 = module_0.ansible_native_concat(str_0)