# Automatically generated by Pynguin.
import ansible.cli.console as module_0

def test_case_0():
    float_0 = -281.20258
    console_c_l_i_0 = module_0.ConsoleCLI(float_0)

def test_case_1():
    str_0 = 's|71`K)G>{v'
    console_c_l_i_0 = module_0.ConsoleCLI(str_0)
    var_0 = console_c_l_i_0.init_parser()
    str_1 = '_W#S#<p\t/$'
    console_c_l_i_1 = module_0.ConsoleCLI(str_1)
    int_0 = -547
    var_1 = console_c_l_i_1.do_timeout(int_0)

def test_case_2():
    bool_0 = False
    list_0 = [bool_0, bool_0]
    console_c_l_i_0 = module_0.ConsoleCLI(list_0)
    console_c_l_i_1 = module_0.ConsoleCLI(console_c_l_i_0)
    var_0 = console_c_l_i_1.emptyline()
    var_1 = console_c_l_i_0.get_names()

def test_case_3():
    float_0 = 2407.6074
    console_c_l_i_0 = module_0.ConsoleCLI(float_0)
    var_0 = console_c_l_i_0.list_modules()

def test_case_4():
    float_0 = 3044.65792
    console_c_l_i_0 = module_0.ConsoleCLI(float_0)
    var_0 = console_c_l_i_0.emptyline()

def test_case_5():
    bytes_0 = b'\x1c\x98<\x90\xc7\x81O|\x14\xa8\xd2\xf2\xeb'
    float_0 = -281.20258
    console_c_l_i_0 = module_0.ConsoleCLI(float_0)
    set_0 = {bytes_0}
    var_0 = console_c_l_i_0.do_verbosity(set_0)

def test_case_6():
    str_0 = '0KxL'
    float_0 = 3162.493199
    console_c_l_i_0 = module_0.ConsoleCLI(float_0)
    var_0 = console_c_l_i_0.do_become_method(str_0)
    bytes_0 = b'\x80='
    console_c_l_i_1 = module_0.ConsoleCLI(bytes_0)
    var_1 = console_c_l_i_1.cmdloop()

def test_case_7():
    str_0 = 's|71`K)G>{v'
    console_c_l_i_0 = module_0.ConsoleCLI(str_0)
    var_0 = console_c_l_i_0.init_parser()
    str_1 = '_W#S#<p\t/$'
    console_c_l_i_1 = module_0.ConsoleCLI(str_1)
    float_0 = 1.0
    int_0 = -547
    var_1 = console_c_l_i_1.do_timeout(int_0)
    console_c_l_i_2 = module_0.ConsoleCLI(float_0)
    var_2 = console_c_l_i_2.do_diff(console_c_l_i_1)

def test_case_8():
    str_0 = 'I%WQ4oS3x9XB\\5t0'
    bool_0 = True
    console_c_l_i_0 = module_0.ConsoleCLI(bool_0)
    var_0 = console_c_l_i_0.do_timeout(str_0)

def test_case_9():
    str_0 = '$Lhb8~'
    console_c_l_i_0 = module_0.ConsoleCLI(str_0)
    list_0 = [str_0, str_0]
    console_c_l_i_1 = module_0.ConsoleCLI(list_0)
    var_0 = console_c_l_i_1.run()
    dict_0 = {}
    var_1 = console_c_l_i_1.do_cd(dict_0)

def test_case_10():
    str_0 = 'ivx3_na\r\\`H$H2jT5'
    console_c_l_i_0 = module_0.ConsoleCLI(str_0)
    var_0 = console_c_l_i_0.get_names()
    bytes_0 = b'I\xa0\xa39\xfb \xc3r\x9bY22'
    str_1 = '['
    dict_0 = None
    float_0 = 557.0
    var_1 = console_c_l_i_0.complete_cd(str_0, str_1, dict_0, float_0)
    list_0 = [console_c_l_i_0, bytes_0]
    var_2 = console_c_l_i_0.do_timeout(str_0)
    bool_0 = True
    console_c_l_i_1 = module_0.ConsoleCLI(bool_0)
    var_3 = console_c_l_i_1.do_become_method(list_0)
    var_4 = console_c_l_i_1.do_become_method(console_c_l_i_0)

def test_case_11():
    tuple_0 = None
    bytes_0 = b'\xea\x13\x88\xaf'
    list_0 = [bytes_0, bytes_0, bytes_0, bytes_0]
    console_c_l_i_0 = module_0.ConsoleCLI(list_0)
    var_0 = console_c_l_i_0.do_check(tuple_0)
    bytes_1 = b'\x8f\x06'
    str_0 = 'awaiting_prompt'
    console_c_l_i_1 = module_0.ConsoleCLI(bytes_1)
    var_1 = console_c_l_i_1.list_modules()
    var_2 = console_c_l_i_1.do_become_method(str_0)
    console_c_l_i_2 = module_0.ConsoleCLI(bytes_1)
    var_3 = console_c_l_i_2.cmdloop()

def test_case_12():
    str_0 = 'Eup'
    tuple_0 = (str_0,)
    set_0 = {str_0, tuple_0, str_0}
    console_c_l_i_0 = module_0.ConsoleCLI(set_0)
    float_0 = 418.64
    var_0 = console_c_l_i_0.do_timeout(float_0)
    int_0 = 2658
    console_c_l_i_1 = module_0.ConsoleCLI(int_0)
    var_1 = console_c_l_i_1.do_diff(int_0)

def test_case_13():
    float_0 = 1.5
    list_0 = [float_0, float_0]
    float_1 = -2005.0
    str_0 = '\n        Finds the active state, recursively if necessary when there are child states.\n        '
    bytes_0 = b'\xa7|\xea\x9fQ'
    console_c_l_i_0 = module_0.ConsoleCLI(bytes_0)
    var_0 = console_c_l_i_0.do_become_method(str_0)
    str_1 = '::P&cNBb8,Y'
    dict_0 = {float_1: list_0, float_0: list_0, console_c_l_i_0: var_0, float_0: console_c_l_i_0}
    console_c_l_i_1 = module_0.ConsoleCLI(dict_0)
    var_1 = console_c_l_i_1.do_become_method(str_1)
    bool_0 = False
    tuple_0 = (console_c_l_i_0, bool_0)
    var_2 = console_c_l_i_1.do_check(tuple_0)
    bytes_1 = b'\x9c\xb8\xea\x96\x08f\x0e\x96\x9fnV*\x80""]}\xd8\x05\x8e'
    var_3 = console_c_l_i_1.do_timeout(bytes_1)

def test_case_14():
    bool_0 = False
    str_0 = ''
    set_0 = {str_0, str_0, str_0, str_0}
    console_c_l_i_0 = module_0.ConsoleCLI(set_0)
    var_0 = console_c_l_i_0.do_become_method(bool_0)
    str_1 = ')Ynz"\tjA\rWWYn#IB'
    console_c_l_i_1 = module_0.ConsoleCLI(str_1)
    set_1 = {str_1, str_1}
    var_1 = console_c_l_i_1.do_timeout(set_1)
    bool_1 = False
    var_2 = console_c_l_i_1.do_exit(str_0)
    var_3 = console_c_l_i_1.do_exit(str_1)
    dict_0 = None
    float_0 = -2605.0
    tuple_0 = (dict_0, float_0)
    var_4 = console_c_l_i_1.do_verbosity(tuple_0)
    var_5 = console_c_l_i_1.do_check(tuple_0)
    var_6 = console_c_l_i_1.do_forks(bool_1)

def test_case_15():
    bytes_0 = b'dF\x0e\xfd<\xd8\x81_'
    float_0 = 177.292
    list_0 = [float_0]
    console_c_l_i_0 = module_0.ConsoleCLI(list_0)
    var_0 = console_c_l_i_0.do_timeout(bytes_0)
    str_0 = '_}j)`\x0cLDRc'
    list_1 = [str_0, str_0]
    dict_0 = None
    bytes_1 = b'\xe4\xa9\xf2\xe4'
    var_1 = console_c_l_i_0.complete_cd(list_1, str_0, dict_0, bytes_1)
    float_1 = 333.294919
    var_2 = console_c_l_i_0.cmdloop()
    str_1 = 'G\t* }+IbYh36\r}'
    str_2 = '4'
    dict_1 = {str_0: str_0, str_2: var_0, var_0: str_0}
    list_2 = [float_1, dict_1, str_2]
    var_3 = console_c_l_i_0.get_names()
    tuple_0 = (str_1, str_2, dict_1, list_2)
    console_c_l_i_1 = module_0.ConsoleCLI(tuple_0)
    var_4 = console_c_l_i_1.emptyline()
    console_c_l_i_2 = module_0.ConsoleCLI(str_0)
    var_5 = console_c_l_i_2.list_modules()
    set_0 = None
    var_6 = console_c_l_i_1.do_forks(set_0)
    var_7 = console_c_l_i_1.do_verbosity(tuple_0)
    console_c_l_i_3 = module_0.ConsoleCLI(float_1)
    str_3 = '#'
    var_8 = console_c_l_i_0.do_shell(str_3)

def test_case_16():
    str_0 = '>oK'
    str_1 = 'c('
    console_c_l_i_0 = module_0.ConsoleCLI(str_1)
    var_0 = console_c_l_i_0.run()
    console_c_l_i_1 = module_0.ConsoleCLI(str_0)
    float_0 = 4118.606503567441
    console_c_l_i_2 = module_0.ConsoleCLI(str_0)
    var_1 = console_c_l_i_2.do_verbosity(float_0)
    int_0 = 1904
    var_2 = console_c_l_i_1.do_verbosity(int_0)
    str_2 = ': i$\nvs\t4*AFC'
    var_3 = console_c_l_i_0.do_shell(str_2)

def test_case_17():
    str_0 = '=FsU`S|rL-"Daj54s3%\n'
    str_1 = 'c('
    console_c_l_i_0 = module_0.ConsoleCLI(str_1)
    var_0 = console_c_l_i_0.run()
    console_c_l_i_1 = module_0.ConsoleCLI(str_0)
    console_c_l_i_2 = module_0.ConsoleCLI(console_c_l_i_0)
    var_1 = console_c_l_i_1.list_modules()
    float_0 = 4118.606503567441
    str_2 = 'Th}G"\\AGL>"E?_ (3r\nb'
    console_c_l_i_3 = module_0.ConsoleCLI(str_2)
    var_2 = console_c_l_i_3.do_verbosity(float_0)
    var_3 = console_c_l_i_0.do_shell(str_0)