# Automatically generated by Pynguin.
import ansible.modules.systemd as module_0

def test_case_0():
    try:
        str_0 = 'JJeW\rwi!"2{N{=H['
        var_0 = module_0.request_was_ignored(str_0)
        float_0 = 3185.0
        var_1 = module_0.is_running_service(float_0)
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = "'{>;>((|'UZCz\t"
        var_0 = module_0.is_deactivating_service(str_0)
    except BaseException:
        pass

def test_case_2():
    try:
        int_0 = -2622
        var_0 = module_0.request_was_ignored(int_0)
    except BaseException:
        pass

def test_case_3():
    try:
        bytes_0 = b'\xcexPI\xf0\xf4'
        var_0 = module_0.parse_systemctl_show(bytes_0)
    except BaseException:
        pass