# Automatically generated by Pynguin.
import httpie.models as module_0

def test_case_0():
    try:
        bytes_0 = b''
        h_t_t_p_message_0 = module_0.HTTPMessage(bytes_0)
        int_0 = 1043
        iterable_0 = h_t_t_p_message_0.iter_body(int_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = 1005
        int_1 = 0
        h_t_t_p_message_0 = module_0.HTTPMessage(int_1)
        iterable_0 = h_t_t_p_message_0.iter_lines(int_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '\rP0~A6Gy'
        h_t_t_p_response_0 = module_0.HTTPResponse(str_0)
        var_0 = h_t_t_p_response_0.iter_body()
    except BaseException:
        pass

def test_case_3():
    try:
        bytes_0 = b''
        h_t_t_p_message_0 = module_0.HTTPMessage(bytes_0)
        tuple_0 = ()
        h_t_t_p_response_0 = module_0.HTTPResponse(tuple_0)
        var_0 = h_t_t_p_response_0.iter_lines(h_t_t_p_message_0)
    except BaseException:
        pass