# Automatically generated by Pynguin.
import ansible.module_utils.facts.network.hurd as module_0

def test_case_0():
    try:
        bool_0 = False
        hurd_pfinet_network_0 = module_0.HurdPfinetNetwork(bool_0)
        dict_0 = {hurd_pfinet_network_0: hurd_pfinet_network_0, hurd_pfinet_network_0: hurd_pfinet_network_0}
        bytes_0 = None
        str_0 = '!{b-`b*\r9)\t>\x0bm\x0cDZN`'
        tuple_0 = (bytes_0, str_0)
        set_0 = {bytes_0}
        hurd_network_collector_0 = module_0.HurdNetworkCollector()
        hurd_pfinet_network_1 = module_0.HurdPfinetNetwork(hurd_network_collector_0)
        var_0 = hurd_pfinet_network_1.assign_network_facts(dict_0, tuple_0, set_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = -3116.721
        hurd_pfinet_network_0 = module_0.HurdPfinetNetwork(float_0)
        var_0 = hurd_pfinet_network_0.populate()
    except BaseException:
        pass