# Automatically generated by Pynguin.
import ansible.plugins.strategy.linear as module_0

def test_case_0():
    try:
        strategy_module_0 = module_0.StrategyModule()
    except BaseException:
        pass