# Automatically generated by Pynguin.
import pymonet.lazy as module_0
import builtins as module_1

def test_case_0():
    try:
        list_0 = []
        lazy_0 = module_0.Lazy(list_0)
        var_0 = lazy_0.get()
    except BaseException:
        pass

def test_case_1():
    try:
        list_0 = None
        tuple_0 = (list_0,)
        str_0 = 'v:/ixLDC-ZV\x0cp*[(='
        lazy_0 = module_0.Lazy(str_0)
        var_0 = lazy_0.map(tuple_0)
    except BaseException:
        pass

def test_case_2():
    try:
        list_0 = []
        object_0 = module_1.object(*list_0)
        int_0 = -2842
        lazy_0 = module_0.Lazy(int_0)
        callable_0 = None
        str_0 = lazy_0.__str__()
        var_0 = lazy_0.ap(int_0)
        var_1 = lazy_0.map(callable_0)
        var_2 = lazy_0.bind(object_0)
        dict_0 = {str_0: str_0}
        lazy_1 = module_0.Lazy(dict_0)
        bool_0 = lazy_1.__eq__(object_0)
        var_3 = lazy_0.to_validation(*list_0)
    except BaseException:
        pass

def test_case_3():
    try:
        float_0 = -367.75
        lazy_0 = module_0.Lazy(float_0)
        var_0 = lazy_0.to_box()
    except BaseException:
        pass

def test_case_4():
    try:
        list_0 = []
        lazy_0 = module_0.Lazy(list_0)
        var_0 = lazy_0.to_either()
    except BaseException:
        pass

def test_case_5():
    try:
        object_0 = module_1.object()
        lazy_0 = module_0.Lazy(object_0)
        var_0 = lazy_0.to_maybe()
    except BaseException:
        pass

def test_case_6():
    try:
        int_0 = 192
        lazy_0 = module_0.Lazy(int_0)
        var_0 = lazy_0.to_validation()
    except BaseException:
        pass