# Automatically generated by Pynguin.
import ansible.module_utils.facts.utils as module_0

def test_case_0():
    pass

def test_case_1():
    str_0 = 'n.OFC~R'
    var_0 = module_0.get_file_lines(str_0)

def test_case_2():
    bool_0 = False
    var_0 = module_0.get_mount_size(bool_0)
    bytes_0 = b'\xe3\xd9"g\x1b\xd1'
    var_1 = module_0.get_file_lines(bytes_0)

def test_case_3():
    str_0 = '\r2-J+u4u\nm\\=\t'
    var_0 = module_0.get_mount_size(str_0)