# Automatically generated by Pynguin.
import ansible.module_utils.facts.utils as module_0

def test_case_0():
    try:
        tuple_0 = ()
        var_0 = module_0.get_file_lines(tuple_0)
    except BaseException:
        pass

def test_case_1():
    try:
        dict_0 = None
        var_0 = module_0.get_mount_size(dict_0)
    except BaseException:
        pass

def test_case_2():
    try:
        bool_0 = True
        var_0 = module_0.get_file_content(bool_0)
    except BaseException:
        pass

def test_case_3():
    try:
        int_0 = 1676
        bytes_0 = b'.'
        var_0 = module_0.get_file_content(bytes_0, int_0)
    except BaseException:
        pass