# Automatically generated by Pynguin.
import youtube_dl.downloader.http as module_0

def test_case_0():
    try:
        float_0 = 9.8485
        bytes_0 = b'\x82A\x98S\x9dIO\x1b\x89\xda\xdc\xa3\x11\xa5\xfd\x8c\xa4\xfd\xbd\xdd'
        float_1 = 1115.284978
        http_f_d_0 = module_0.HttpFD(float_1, float_1)
        var_0 = http_f_d_0.real_download(float_0, bytes_0)
    except BaseException:
        pass