# Automatically generated by Pynguin.
import ansible.playbook.role.requirement as module_0

def test_case_0():
    role_requirement_0 = module_0.RoleRequirement()

def test_case_1():
    str_0 = "Convert a human-readable string bits value to bits in integer.\n\n    Example: ``check_type_bits('1Mb')`` returns integer 1048576.\n\n    Raises :class:`TypeError` if unable to covert the value.\n    "
    role_requirement_0 = module_0.RoleRequirement()
    var_0 = role_requirement_0.role_yaml_parse(str_0)

def test_case_2():
    str_0 = '@@8'
    role_requirement_0 = module_0.RoleRequirement()
    var_0 = role_requirement_0.role_yaml_parse(str_0)

def test_case_3():
    role_requirement_0 = module_0.RoleRequirement()
    str_0 = 'ZVK,J"B{'
    var_0 = role_requirement_0.role_yaml_parse(str_0)

def test_case_4():
    role_requirement_0 = module_0.RoleRequirement()
    str_0 = 'ghc2,\rN'
    var_0 = role_requirement_0.role_yaml_parse(str_0)
    var_1 = role_requirement_0.role_yaml_parse(var_0)

def test_case_5():
    str_0 = 'vE\t}0\r92\rH4H=r+_'
    role_requirement_0 = module_0.RoleRequirement()
    var_0 = role_requirement_0.role_yaml_parse(str_0)

def test_case_6():
    str_0 = 'http://git.example.com/repos/repo.tar.gz'
    role_requirement_0 = module_0.RoleRequirement()
    var_0 = role_requirement_0.repo_url_to_role_name(str_0)

def test_case_7():
    str_0 = 'http://git.example.com/repos/repo.git'
    role_requirement_0 = module_0.RoleRequirement()
    var_0 = role_requirement_0.repo_url_to_role_name(str_0)