# Automatically generated by Pynguin.
import thefuck.rules.sudo_command_from_user_path as module_0

def test_case_0():
    try:
        bytes_0 = b'B\x1e\x8b\xa8\x9b\xe3d\x8f\x0c\xa8E\x06t\x1aR\xa3'
        var_0 = module_0.get_new_command(bytes_0)
    except BaseException:
        pass