# Automatically generated by Pynguin.
import mimesis.providers.payment as module_0
import mimesis.enums as module_1

def test_case_0():
    payment_0 = module_0.Payment()
    str_0 = payment_0.credit_card_number()

def test_case_1():
    payment_0 = module_0.Payment()
    int_0 = payment_0.cid()
    payment_1 = module_0.Payment()
    str_0 = payment_1.credit_card_number()
    str_1 = payment_0.paypal()

def test_case_2():
    payment_0 = module_0.Payment()
    str_0 = payment_0.paypal()
    str_1 = payment_0.credit_card_number()

def test_case_3():
    payment_0 = module_0.Payment()
    str_0 = payment_0.paypal()
    str_1 = payment_0.paypal()
    str_2 = payment_0.credit_card_number()
    str_3 = payment_0.bitcoin_address()
    int_0 = payment_0.cvv()
    str_4 = payment_0.bitcoin_address()

def test_case_4():
    list_0 = []
    payment_0 = module_0.Payment(*list_0)
    str_0 = payment_0.paypal()
    payment_1 = module_0.Payment()
    int_0 = payment_1.cid()
    str_1 = payment_1.ethereum_address()
    payment_2 = module_0.Payment()
    str_2 = payment_2.credit_card_number()
    str_3 = payment_1.paypal()

def test_case_5():
    payment_0 = module_0.Payment()
    str_0 = payment_0.credit_card_network()
    int_0 = payment_0.cvv()
    payment_1 = module_0.Payment()
    card_type_0 = module_1.CardType.VISA
    str_1 = payment_0.credit_card_network()
    str_2 = payment_1.credit_card_number(card_type_0)
    payment_2 = module_0.Payment()

def test_case_6():
    payment_0 = module_0.Payment()
    dict_0 = payment_0.credit_card_owner()

def test_case_7():
    payment_0 = module_0.Payment()
    dict_0 = payment_0.credit_card_owner()

def test_case_8():
    payment_0 = module_0.Payment()
    int_0 = payment_0.cvv()