# Automatically generated by Pynguin.
import py_backwards.compiler as module_0

def test_case_0():
    try:
        str_0 = None
        int_0 = -1321
        tuple_0 = (int_0, int_0)
        compilation_result_0 = module_0.compile_files(str_0, str_0, tuple_0)
    except BaseException:
        pass

def test_case_1():
    try:
        int_0 = 2361
        str_0 = '/'
        tuple_0 = (int_0, int_0)
        compilation_result_0 = module_0.compile_files(str_0, str_0, tuple_0)
    except BaseException:
        pass

def test_case_2():
    try:
        int_0 = -3020
        str_0 = '/'
        tuple_0 = (int_0, int_0)
        compilation_result_0 = module_0.compile_files(str_0, str_0, tuple_0)
    except BaseException:
        pass