# Automatically generated by Pynguin.
import ansible.utils.version as module_0
import ansible.module_utils.compat.version as module_1

def test_case_0():
    semantic_version_0 = module_0.SemanticVersion()

def test_case_1():
    bytes_0 = b'\xf2\xcf\xa0,,\xe9\xcf\x9f\xd4\xd0s\n\xea\xc3'
    semantic_version_0 = module_0.SemanticVersion()
    alpha_0 = module_0._Alpha(semantic_version_0)
    var_0 = alpha_0.__ne__(bytes_0)

def test_case_2():
    str_0 = 'a'
    alpha_0 = module_0._Alpha(str_0)
    alpha_1 = module_0._Alpha(str_0)
    alpha_2 = module_0._Alpha(str_0)
    str_1 = 'b'
    alpha_3 = module_0._Alpha(str_1)
    alpha_4 = module_0._Alpha(str_0)
    str_2 = '1'
    alpha_5 = module_0._Alpha(str_2)
    alpha_6 = module_0._Alpha(str_1)
    alpha_7 = module_0._Alpha(str_0)
    var_0 = alpha_6 <= alpha_7
    var_1 = alpha_0 <= str_0

def test_case_3():
    semantic_version_0 = module_0.SemanticVersion()
    var_0 = semantic_version_0.__ne__(semantic_version_0)

def test_case_4():
    str_0 = ']gz!\t_\r=8-\rzN9uZQaJk'
    bool_0 = False
    alpha_0 = module_0._Alpha(bool_0)
    var_0 = alpha_0.__ne__(str_0)

def test_case_5():
    semantic_version_0 = module_0.SemanticVersion()
    semantic_version_1 = module_0.SemanticVersion()
    var_0 = semantic_version_0.__ne__(semantic_version_1)
    bool_0 = False
    numeric_0 = module_0._Numeric(bool_0)
    str_0 = 'l3h(RM:;+P&'
    var_1 = numeric_0.__eq__(str_0)
    var_2 = numeric_0.__gt__(bool_0)

def test_case_6():
    str_0 = '1.2.3-alpha.1'
    loose_version_0 = module_1.LooseVersion(str_0)
    semantic_version_0 = module_0.SemanticVersion(str_0)
    loose_version_1 = module_1.LooseVersion()

def test_case_7():
    str_0 = '1.2.3-alpha.1'
    loose_version_0 = module_1.LooseVersion(str_0)
    semantic_version_0 = module_0.SemanticVersion(str_0)
    str_1 = '1.2.3+20130313144700'
    loose_version_1 = module_1.LooseVersion(str_1)
    semantic_version_1 = module_0.SemanticVersion(str_1)
    str_2 = '1.2.3-alpha.1+20130313144700'
    loose_version_2 = module_1.LooseVersion(str_2)

def test_case_8():
    str_0 = '1.2.3'
    loose_version_0 = module_1.LooseVersion(str_0)
    semantic_version_0 = module_0.SemanticVersion(str_0)
    str_1 = '1.2.3+build.123'
    loose_version_1 = module_1.LooseVersion(str_1)
    semantic_version_1 = module_0.SemanticVersion(str_1)
    str_2 = '1.2.3-alpha.1'
    loose_version_2 = module_1.LooseVersion(str_2)
    semantic_version_2 = module_0.SemanticVersion(str_2)
    str_3 = '1.2.3-alpha.1+build.123'
    loose_version_3 = module_1.LooseVersion(str_3)