# Automatically generated by Pynguin.
import ansible.module_utils.common.arg_spec as module_0

def test_case_0():
    try:
        module_argument_spec_validator_0 = module_0.ModuleArgumentSpecValidator()
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = 'vl:p6*RW{U9Z'
        validation_result_0 = module_0.ValidationResult(str_0)
        module_argument_spec_validator_0 = module_0.ModuleArgumentSpecValidator()
    except BaseException:
        pass

def test_case_2():
    try:
        int_0 = 263
        list_0 = [int_0, int_0, int_0]
        list_1 = []
        argument_spec_validator_0 = module_0.ArgumentSpecValidator(list_0, list_1, list_1)
    except BaseException:
        pass

def test_case_3():
    try:
        str_0 = 'str'
        int_0 = -3870
        str_1 = 'aliases'
        str_2 = {str_1: str_0, str_1: str_1}
        var_0 = {str_0: int_0, str_0: int_0, str_0: str_2}
        argument_spec_validator_0 = module_0.ArgumentSpecValidator(var_0)
        var_1 = argument_spec_validator_0.validate(str_1)
    except BaseException:
        pass

def test_case_4():
    try:
        int_0 = 3388
        dict_0 = {}
        list_0 = [dict_0]
        module_argument_spec_validator_0 = module_0.ModuleArgumentSpecValidator(*list_0)
        var_0 = module_argument_spec_validator_0.validate(int_0)
    except BaseException:
        pass

def test_case_5():
    try:
        str_0 = 'required'
        str_1 = 'str'
        str_2 = '\nHPq=h"!;Uhmf#\n'
        str_3 = 'inP'
        int_0 = -3870
        var_0 = {str_2: int_0}
        str_4 = {str_0: str_1, str_1: str_2}
        var_1 = {str_1: int_0, str_2: var_0, str_1: str_4}
        str_5 = {str_0: str_0, str_0: str_0, str_3: str_2}
        argument_spec_validator_0 = module_0.ArgumentSpecValidator(var_1)
        var_2 = argument_spec_validator_0.validate(str_5)
    except BaseException:
        pass