# Automatically generated by Pynguin.
import mimesis.random as module_0

def test_case_0():
    random_0 = module_0.Random()

def test_case_1():
    random_0 = module_0.Random()

def test_case_2():
    random_0 = module_0.Random()
    str_0 = random_0.custom_code()
    str_1 = random_0.generate_string(str_0)

def test_case_3():
    random_0 = module_0.Random()
    str_0 = random_0.custom_code()

def test_case_4():
    random_0 = module_0.Random()
    float_0 = 4.3
    int_0 = 510
    list_0 = random_0.randints(int_0)
    float_1 = random_0.uniform(float_0, float_0)
    str_0 = random_0.randstr()
    str_1 = 'i#XFnt-\x0c'
    str_2 = random_0.custom_code(str_1)

def test_case_5():
    random_0 = module_0.Random()
    str_0 = random_0.randstr()

def test_case_6():
    random_0 = module_0.Random()
    float_0 = 3600.0
    float_1 = 4.3
    random_1 = module_0.Random()
    int_0 = 510
    list_0 = random_0.randints(int_0)
    float_2 = random_1.uniform(float_0, float_1)
    str_0 = random_1.randstr()
    str_1 = 'i#XFnt-\x0c'
    str_2 = random_0.randstr(int_0)
    str_3 = random_1.custom_code(str_1)