# Automatically generated by Pynguin.
import ansible.module_utils.facts.network.hpux as module_0

def test_case_0():
    try:
        str_0 = 'K'
        h_p_u_x_network_0 = module_0.HPUXNetwork(str_0)
        var_0 = h_p_u_x_network_0.populate()
    except BaseException:
        pass

def test_case_1():
    try:
        str_0 = '\x0by\x0c7ievdwX*+kY'
        h_p_u_x_network_0 = module_0.HPUXNetwork(str_0)
        var_0 = h_p_u_x_network_0.get_default_interfaces()
    except BaseException:
        pass

def test_case_2():
    try:
        bool_0 = False
        h_p_u_x_network_0 = module_0.HPUXNetwork(bool_0)
        var_0 = h_p_u_x_network_0.get_interfaces_info()
    except BaseException:
        pass