# Automatically generated by Pynguin.
import ansible.plugins.inventory.auto as module_0

def test_case_0():
    try:
        inventory_module_0 = module_0.InventoryModule()
        str_0 = '&1{HK?mJ1hN}5ND\r*'
        inventory_module_1 = module_0.InventoryModule()
        var_0 = inventory_module_1.parse(inventory_module_0, inventory_module_0, str_0)
    except BaseException:
        pass