# Automatically generated by Pynguin.
import ansible.plugins.lookup.fileglob as module_0

def test_case_0():
    try:
        lookup_module_0 = module_0.LookupModule()
        str_0 = 't0RTAj\rS}0X;RWnG\t'
        var_0 = lookup_module_0.run(str_0)
    except BaseException:
        pass

def test_case_1():
    try:
        lookup_module_0 = module_0.LookupModule()
        dict_0 = {}
        var_0 = lookup_module_0.run(dict_0)
        str_0 = 'v(\rwi8-YR>G.A'
        var_1 = lookup_module_0.run(str_0, **dict_0)
    except BaseException:
        pass

def test_case_2():
    try:
        str_0 = '|rS\nW"!VCriTmC\ta3/<P'
        dict_0 = {str_0: str_0}
        str_1 = 'w3T^m&X,\x0cfG}'
        list_0 = [str_1, str_1]
        str_2 = '[io'
        dict_1 = {str_2: str_1}
        lookup_module_0 = module_0.LookupModule(list_0, **dict_1)
        var_0 = lookup_module_0.run(dict_0, str_0)
    except BaseException:
        pass

def test_case_3():
    try:
        lookup_module_0 = module_0.LookupModule()
        str_0 = '4{bOo.tN\x0c'
        var_0 = lookup_module_0.run(str_0, str_0)
    except BaseException:
        pass