# Automatically generated by Pynguin.
import ansible.playbook.play as module_0

def test_case_0():
    try:
        int_0 = 254
        bool_0 = True
        play_0 = module_0.Play()
        var_0 = play_0.get_roles()
        play_1 = module_0.Play()
        var_1 = play_1.load(int_0, bool_0)
    except BaseException:
        pass

def test_case_1():
    try:
        play_0 = module_0.Play()
        var_0 = play_0.deserialize(play_0)
    except BaseException:
        pass

def test_case_2():
    try:
        play_0 = module_0.Play()
        var_0 = play_0.compile()
        play_1 = module_0.Play()
        var_1 = play_1.get_vars()
        var_2 = play_1.copy()
        var_3 = play_1.serialize()
        bytes_0 = b'\x1b\x05\xfd\xdbT\xa9K\xceHZ\x17i'
        complex_0 = None
        set_0 = {play_0}
        tuple_0 = (set_0, complex_0)
        var_4 = play_0.load(bytes_0, complex_0, tuple_0, bytes_0)
    except BaseException:
        pass