# Automatically generated by Pynguin.
import mimesis.providers.address as module_0

def test_case_0():
    try:
        address_0 = module_0.Address()
        str_0 = address_0.federal_subject()
        list_0 = []
        str_1 = address_0.region(*list_0)
        str_2 = address_0.street_number()
        dict_0 = {str_0: str_0, str_0: address_0, str_0: address_0}
        str_3 = address_0.postal_code()
        str_4 = address_0.prefecture(**dict_0)
    except BaseException:
        pass

def test_case_1():
    try:
        address_0 = module_0.Address()
        var_0 = address_0.latitude()
        str_0 = address_0.postal_code()
        int_0 = 300
        str_1 = address_0.street_number(int_0)
        str_2 = address_0.city()
        str_3 = address_0.calling_code()
        list_0 = None
        dict_0 = {list_0: list_0, list_0: list_0, list_0: list_0}
        bool_0 = True
        str_4 = address_0.country(bool_0)
        str_5 = address_0.street_name()
        str_6 = address_0.prefecture()
        bool_1 = False
        str_7 = address_0.country(bool_1)
        list_1 = [dict_0]
        address_1 = module_0.Address(*list_1)
    except BaseException:
        pass