# Automatically generated by Pynguin.
import ansible.plugins.action.set_fact as module_0

def test_case_0():
    try:
        bool_0 = True
        float_0 = 432.2539
        dict_0 = {float_0: float_0}
        str_0 = '~>\n/h.DAvc'
        str_1 = '%FrBLw(lP<"?p0I\x0c'
        bool_1 = False
        action_module_0 = module_0.ActionModule(float_0, dict_0, str_0, str_1, bool_1, dict_0)
        var_0 = action_module_0.run(bool_0)
    except BaseException:
        pass

def test_case_1():
    try:
        float_0 = 0.0001
        action_module_0 = None
        bytes_0 = b'\x19bi'
        bool_0 = True
        bool_1 = False
        set_0 = {bool_1, bool_1, bytes_0}
        list_0 = [bool_0, set_0, action_module_0, float_0]
        dict_0 = {bytes_0: bool_0, bool_1: set_0}
        action_module_1 = module_0.ActionModule(bool_0, bytes_0, set_0, list_0, bytes_0, dict_0)
        float_1 = 2125.196258
        var_0 = action_module_1.run(list_0, float_1)
    except BaseException:
        pass